#ifdef BUILD_COLECO

/*
  Graphics functionality - ColecoVision TMS9918A

  GRAPHICS II driven as a cellmap: z88dk's vdp_set_mode(2) lays down the
  identity name table (0..255 per screen third) and it is never touched again,
  so every 32x24 cell owns its own 8 pattern bytes (y*256 + x*8) and 8 color
  bytes (0x2000 + the same). Drawing a cell is two 8-byte VRAM writes; there is
  no glyph budget, no RAM shadow, and the msdos tile vocabulary carries over
  verbatim as indices into the tiles[] ROM array.

  Ported from src/msdos/graphics.c (the look) for the ColecoVision FujiNet
  cartridge bring-up; the same layout is the template for the Adam re-port.
*/

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <video/tms99x8.h>
#include <interrupt.h>
#include "vars.h"
#include "../misc.h"

/**
 * @brief character set arrays, generated by support/coleco/make_charset.py
 * tiles: 8 pattern bytes then 8 per-row fg<<4|bg color bytes
 * font:  1bpp ASCII 0x20-0x7F, colored at draw time
 */
extern const unsigned char tiles[];
extern const unsigned char font[];

#define GLYPH(n) (font + ((unsigned int)(n) << 3))

/**
 * @brief resolve a sheet index to its tile data. The generated tiles[] only
 * carries the referenced spans - 0x00-0x60, then the 0x82-0xE8 dim/animation
 * run - so indices from 0x82 up shift down by the dropped 0x61-0x81 gap.
 * Keep in step with support/coleco/make_charset.py's TILE_KEEP.
 */
static const unsigned char *tilePtr(unsigned char n)
{
    if (n >= 0x82)
        n -= 0x21;
    return tiles + ((unsigned int)n << 4);
}

#define TILE(n) tilePtr(n)

// Per-row color attributes (TMS fg<<4 | bg): dark blue field, white text,
// light red alt text, white-on-red selected name, blue-on-cyan idle name.
#define TMS_DARK_BLUE 4
#define TMS_CYAN 7
#define TMS_MED_RED 8
#define TMS_LIGHT_RED 9
#define TMS_WHITE 15

#define A_TEXT ((TMS_WHITE << 4) | TMS_DARK_BLUE)
#define A_ALT ((TMS_LIGHT_RED << 4) | TMS_DARK_BLUE)
#define A_NAME_ACTIVE ((TMS_WHITE << 4) | TMS_MED_RED)
#define A_NAME_IDLE ((TMS_DARK_BLUE << 4) | TMS_CYAN)

// Color table base in the z88dk mode 2 layout (pattern table is at 0x0000)
#define CT_BASE 0x2000

// util.c
extern void myInt(void);

// The SN76489, write only. sound.c owns the effects; this one is here so
// initGraphics() can silence power-on noise before the first (long) network
// transaction - the 55AA cartridge header path skips the BIOS silencing.
__sfr __at 0xFF psg_port_init;

/**
 * @brief Top left of each playfield quadrant (32x24 layout)
 */
static const unsigned char quadrant_offset[4][2] =
    {
        {5, 12}, // bottom left
        {5, 1},  // Top left
        {17, 1}, // top right
        {17, 12} // bottom right
    };

/**
 * @brief offset of legends for each player
 */
static const signed char legendShipOffset[5][2] =
    {
        {2, 0},
        {1, 0},
        {0, 0},
        {0, 5},
        {1, 6},
    };

/**
 * @brief Horizontal Field offset
 */
static unsigned char fieldX = 0;

/**
 * @brief Number of active players
 */
static unsigned char playerCount = 0;

/**
 * @brief plot a tile (8 pattern + 8 color bytes) at column x, row y
 */
static void plotTile(const unsigned char *tile, unsigned char x, unsigned char y)
{
    unsigned int addr;

    if (x >= WIDTH || y >= HEIGHT)
        return;

    addr = ((unsigned int)y << 8) + ((unsigned int)x << 3);
    vdp_vwrite((void *)tile, addr, 8);
    vdp_vwrite((void *)(tile + 8), CT_BASE + addr, 8);
}

/**
 * @brief plot two tiles merged (patterns OR'd) at column x, row y.
 * Used for the one row the top and bottom board borders share on a 24-row
 * screen (msdos has 25) - each row's color comes from whichever tile has
 * pixels there.
 */
static void plotTilePair(unsigned char a, unsigned char b, unsigned char x, unsigned char y)
{
    unsigned char tmp[16];
    const unsigned char *ta = TILE(a);
    const unsigned char *tb = TILE(b);
    unsigned char i;

    for (i = 0; i < 8; i++)
    {
        tmp[i] = ta[i] | tb[i];
        tmp[i + 8] = ta[i] ? ta[i + 8] : (tb[i] ? tb[i + 8] : ta[i + 8]);
    }

    plotTile(tmp, x, y);
}

/**
 * @brief plot char in the given per-row color attribute
 */
static void plotChar(unsigned char x, unsigned char y, unsigned char attr, char c)
{
    unsigned int addr;
    unsigned char g = (unsigned char)c - 0x20;

    if (x >= WIDTH || y >= HEIGHT)
        return;
    if (g >= 96)
        g = 0;

    addr = ((unsigned int)y << 8) + ((unsigned int)x << 3);
    vdp_vwrite((void *)GLYPH(g), addr, 8);
    vdp_vfill(CT_BASE + addr, attr, 8);
}

/**
 * @brief plot name text on its label background color
 */
static void plotName(unsigned char x, unsigned char y, unsigned char attr, const char *s)
{
    char c;

    while (c = *s++)
    {
        plotChar(x++, y, attr, c);
    }
}

/**
 * @brief Clear screen to the blue field
 */
void resetScreen(void)
{
    waitvsync();
    vdp_vfill(0x0000, 0x00, 0x1800);
    vdp_vfill(CT_BASE, A_TEXT, 0x1800);
}

/**
 * @brief cycle to next color palette
 */
unsigned char cycleNextColor()
{
    return 0;
}

/**
 * @brief Initialize Graphics mode
 * @verbose GRAPHICS II as a 32x24 cellmap
 */
void initGraphics()
{
    psg_port_init = 0x9F; // silence all four SN76489 channels
    psg_port_init = 0xBF;
    psg_port_init = 0xDF;
    psg_port_init = 0xFF;

    vdp_set_mode(2); // clears VRAM, writes the identity name table
    vdp_vfill(CT_BASE, A_TEXT, 0x1800);
    vdp_set_reg(7, TMS_DARK_BLUE); // border matches the field
    vdp_vpoke(0x1B00, 208);        // sprite Y=208: no sprites, ever

    add_raster_int(myInt);
}

/**
 * @brief Reset graphics mode - nothing to reset, the cart never exits
 */
void resetGraphics(void)
{
}

/**
 * @brief Store screen buffer - not supported (no RAM for a shadow);
 * the shared core redraws instead
 */
bool saveScreenBuffer()
{
    return false;
}

void restoreScreenBuffer()
{
}

/**
 * @brief Text output
 */
void drawText(unsigned char x, unsigned char y, const char *s)
{
    char c;
    while (c = *s++)
    {
        if (x >= WIDTH)
        {
            x = 0;
            y++;
        }

        plotChar(x++, y, A_TEXT, c);
    }
}

void drawTextAlt(unsigned char x, unsigned char y, const char *s)
{
    char c;
    while (c = *s++)
    {
        if (c >= 'A' && c <= 'Z')
        {
            plotChar(x++, y, A_ALT, c);
        }
        else
        {
            plotChar(x++, y, A_TEXT, c);
        }
    }
}

/**
 * @brief draw icon (tile) from the msdos sheet
 */
void drawIcon(unsigned char x, unsigned char y, unsigned char icon)
{
    plotTile(TILE(icon), x, y);
}

void drawBlank(unsigned char x, unsigned char y)
{
    plotTile(TILE(0x00), x, y);
}

void drawSpace(unsigned char x, unsigned char y, unsigned char w)
{
    while (w--)
        drawBlank(x++, y);
}

void drawClock(void)
{
    drawIcon(WIDTH - 1, HEIGHT - 1, 0x1D);
}

void drawConnectionIcon(bool show)
{
    if (show)
    {
        drawIcon(0, HEIGHT - 1, 0x1E);
        drawIcon(1, HEIGHT - 1, 0x1F);
    }
    else
    {
        drawIcon(0, HEIGHT - 1, 0x00);
        drawIcon(1, HEIGHT - 1, 0x00);
    }
}

/**
 * @brief true when this player's board shares its middle border row (row 11)
 * with the board above/below it, which happens whenever that counterpart is
 * actually drawn
 */
static bool sharedBorderRow(unsigned char player)
{
    if (player == 0)
        return playerCount >= 2;
    if (player == 2)
        return playerCount == 4;
    return true; // 1 always has 0 below; 3 only exists in 4-player
}

/**
 * @brief Draw Player Name plate and board chrome
 */
void drawPlayerName(unsigned char player, const char *name, bool active)
{
    uint8_t x = quadrant_offset[player][0] - 1;
    uint8_t y = quadrant_offset[player][1] - 1;
    uint8_t add = active ? 0x00 : 0x80;
    uint8_t i = 0;
    bool shared = sharedBorderRow(player);

    x += fieldX;

    if (player == 0 || player == 3)
    {
        // Bottom player boards

        // Thin horizontal border (row 11, shared with the top board's lower
        // border when both are on screen - merge the two tile sets)
        if (shared)
        {
            plotTilePair(0x08 + add, 0x0A + add, x, y);
            for (i = 1; i < 11; i++)
            {
                plotTilePair(0x27 + add, 0x29 + add, x + i, y);
            }
            plotTilePair(0x09 + add, 0x0B + add, x + 11, y);
        }
        else
        {
            drawIcon(x, y, 0x08 + add);
            for (i = 1; i < 11; i++)
            {
                drawIcon(x + i, y, 0x27 + add);
            }
            drawIcon(x + 11, y, 0x09 + add);
        }

        // Name label
        drawIcon(x, y + 11, 0x5E + add);
        for (i = 1; i < 11; i++)
        {
            drawIcon(x + i, y + 11, 0x60 + add);
        }
        drawIcon(x + 11, y + 11, 0x5F + add);
        plotName(x + 2, y + 11, active ? A_NAME_ACTIVE : A_NAME_IDLE, name);

        // Active indicator
        if (active)
            drawIcon(x + 1, y + 11, 0x5B);

        // Bottom border below name label
        drawIcon(x, y + 12, 0x20 + add);
        for (i = 1; i < 11; i++)
        {
            drawIcon(x + i, y + 12, 0x28 + add);
        }
        drawIcon(x + 11, y + 12, 0x21 + add);
    }
    else
    {
        // Top player boards

        // Name label
        drawIcon(x, y, 0x5C + add);
        for (i = 1; i < 11; i++)
        {
            drawIcon(x + i, y, 0x60 + add);
        }
        drawIcon(x + 11, y, 0x5D + add);
        plotName(x + 2, y, active ? A_NAME_ACTIVE : A_NAME_IDLE, name);

        // Active indicator
        if (active)
            drawIcon(x + 1, y, 0x5B);

        // Thin Horizontal Border (row 11, see above)
        if (shared)
        {
            plotTilePair(0x0A + add, 0x08 + add, x, y + 11);
            for (i = 1; i < 11; i++)
            {
                plotTilePair(0x29 + add, 0x27 + add, x + i, y + 11);
            }
            plotTilePair(0x0B + add, 0x09 + add, x + 11, y + 11);
        }
        else
        {
            drawIcon(x, y + 11, 0x0A + add);
            for (i = 1; i < 11; i++)
            {
                drawIcon(x + i, y + 11, 0x29 + add);
            }
            drawIcon(x + 11, y + 11, 0x0B + add);
        }
    }

    // Draw left/right borders and drawers
    if (player > 1 || playerCount == 2 && player > 0)
    {
        // Right drawer
        // top
        drawIcon(x + 11, y + 1, 0x25 + add);
        drawIcon(x + 12, y + 1, 0x31 + add);
        drawIcon(x + 13, y + 1, 0x31 + add);
        drawIcon(x + 14, y + 1, 0x31 + add);
        drawIcon(x + 15, y + 1, 0x2D + add);
        drawIcon(x, y + 1, 0x22 + add);

        // Edges
        for (i = 0; i < 8; i++)
        {
            drawIcon(x + 11, y + 2 + i, 0x03 + add);
            drawIcon(x + 15, y + 2 + i, 0x02 + add);
            drawIcon(x, y + 2 + i, 0x22 + add);
        }

        // bottom
        drawIcon(x, y + 10, 0x22 + add);
        drawIcon(x + 11, y + 10, 0x25 + add);
        drawIcon(x + 12, y + 10, 0x31 + add);
        drawIcon(x + 13, y + 10, 0x31 + add);
        drawIcon(x + 14, y + 10, 0x31 + add);
        drawIcon(x + 15, y + 10, 0x2F + add);
    }
    else
    {
        // Left drawer
        drawIcon(x - 4, y + 1, 0x2C + add);
        drawIcon(x - 3, y + 1, 0x31 + add);
        drawIcon(x - 2, y + 1, 0x31 + add);
        drawIcon(x - 1, y + 1, 0x31 + add);
        drawIcon(x, y + 1, 0x24 + add);
        drawIcon(x + 11, y + 1, 0x23 + add);

        // Edges
        for (i = 0; i < 8; i++)
        {
            drawIcon(x - 4, y + 2 + i, 0x02 + add);
            drawIcon(x, y + 2 + i, 0x02 + add);
            drawIcon(x + 11, y + 2 + i, 0x23 + add);
        }

        drawIcon(x - 4, y + 10, 0x2E + add);
        drawIcon(x - 3, y + 10, 0x31 + add);
        drawIcon(x - 2, y + 10, 0x31 + add);
        drawIcon(x - 1, y + 10, 0x31 + add);
        drawIcon(x, y + 10, 0x24 + add);
        drawIcon(x + 11, y + 10, 0x23 + add);
    }
}

/**
 * @brief Draw the board
 */
void drawBoard(unsigned char currentPlayerCount)
{
    unsigned char i;
    playerCount = currentPlayerCount;

    fieldX = playerCount > 2 ? 0 : 6;

    for (i = 0; i < playerCount; i++)
    {
        drawPlayerName(i, "", false);
    }
}

/**
 * @brief draw a horizontal line of w characters at x,y
 */
void drawLine(unsigned char x, unsigned char y, unsigned char w)
{
    while (w--)
        plotTile(TILE(0x3F), x++, y);
}

/**
 * @brief draw ship, shared between a few routines
 */
static void drawShipInternal(unsigned char x, unsigned char y, unsigned char size, unsigned char delta)
{
    uint8_t c = delta ? 0x37 : 0x32;

    if (delta)
    {
        // Vertical
        drawIcon(x, y++, c--); // top

        while (size > 2) // middle
        {
            drawIcon(x, y++, c);
            size--;
        }

        c--; // bottom
        drawIcon(x, y++, c);
    }
    else
    {
        // Horizontal
        drawIcon(x++, y, c++); // Left

        while (size > 2) // middle
        {
            drawIcon(x++, y, c);
            size--;
        }

        c++; // Right
        drawIcon(x++, y, c);
    }
}

/**
 * @brief Draw ship at position on sea
 */
void drawShip(unsigned char quadrant, unsigned char size, unsigned char pos, bool hide)
{
    uint8_t delta = 0;
    uint8_t x = 0, y = 0, i = 0;

    if (pos > 99)
    {
        delta = 1;
        pos -= 100;
    }

    x = pos % 10;
    y = pos / 10;

    x += fieldX + quadrant_offset[quadrant][0];
    y += quadrant_offset[quadrant][1];

    if (hide)
    {
        if (!delta)
        {
            for (i = 0; i < size; i++)
            {
                drawIcon(x++, y, 0x38);
            }
        }
        else
        {
            for (i = 0; i < size; i++)
            {
                drawIcon(x, y++, 0x38);
            }
        }
    }
    else
    {
        drawShipInternal(x, y, size, delta);
    }
}

/**
 * @brief Draw a ship in the drawer
 */
void drawLegendShip(uint8_t player, uint8_t index, uint8_t size, uint8_t status)
{
    uint8_t i = 0;
    uint8_t x = quadrant_offset[player][0] + fieldX + legendShipOffset[index][0];
    uint8_t y = quadrant_offset[player][1] + legendShipOffset[index][1];

    if (player > 1 || (player > 0 && fieldX > 0))
    {
        y++;
        x += 11;
    }
    else
    {
        y++;
        x -= 4;
    }

    if (status)
    {
        drawShipInternal(x, y, size, 1); // draw a nice vertical ship
    }
    else
    {
        // Draw the red splats, instead
        for (i = 0; i < size; i++)
            drawIcon(x, y + i, 0x1C);
    }
}

/**
 * @brief Draw game field for given quadrant
 */
void drawGamefield(uint8_t quadrant, uint8_t *field)
{
    uint8_t ix = 0, iy = 0;
    uint8_t x = quadrant_offset[quadrant][0] + fieldX;
    uint8_t y = quadrant_offset[quadrant][1];

    for (iy = 0; iy < 10; iy++)
    {
        for (ix = 0; ix < 10; ix++)
        {
            if (*field)
            {
                drawIcon(x + ix, y + iy, *field == 1 ? 0x39 : 0xE1);
            }
            field++;
        }
    }
}

void drawGamefieldUpdate(uint8_t quadrant, uint8_t *gamefield, uint8_t attackPos, uint8_t anim)
{
    uint8_t x = quadrant_offset[quadrant][0] + fieldX + (attackPos % 10);
    uint8_t y = quadrant_offset[quadrant][1] + (attackPos / 10);
    uint8_t c = gamefield[attackPos];

    // Animate attack
    if (anim > 9)
    {
        drawIcon(x, y, 217 + anim);
        return;
    }

    if (c == FIELD_ATTACK)
    {
        drawIcon(x, y, anim ? 0x1B : 0x39);
    }
    else if (c == FIELD_MISS)
    {
        drawIcon(x, y, 0xE1);
    }
}

/**
 * @brief Draw game field cursor
 */
void drawGamefieldCursor(uint8_t quadrant, uint8_t x, uint8_t y, uint8_t *gamefield, uint8_t blink)
{
    unsigned char ex = quadrant_offset[quadrant][0] + fieldX + x;
    unsigned char ey = quadrant_offset[quadrant][1] + y;
    unsigned char pos = (y * 10) + x;
    unsigned char c;

    switch (gamefield[pos])
    {
    case FIELD_ATTACK:
        c = 0x43;
        break;
    case FIELD_MISS:
        c = 0x46;
        break;
    default:
        c = 0x40;
        break;
    }

    drawIcon(ex, ey, c + blink);
}

/**
 * @brief Draw end game message
 */
void drawEndgameMessage(const char *message)
{
    uint8_t i, x, ix;
    i = (uint8_t)strlen(message);
    x = WIDTH / 2 - i / 2;

    for (ix = 0; ix < WIDTH; ix++)
        drawIcon(ix, HEIGHT - 2, 0xE2);

    drawSpace(0, HEIGHT - 1, WIDTH);
    drawText(x, HEIGHT - 1, message);
}

/**
 * @brief Draw a box
 */
void drawBox(unsigned char x, unsigned char y, unsigned char w, unsigned char h)
{
    drawIcon(x, y, 0x3B);
    drawIcon(x + w + 1, y, 0x3C);
    drawIcon(x, y + h + 1, 0x3D);
    drawIcon(x + w + 1, y + h + 1, 0x3E);
}

#endif /* BUILD_COLECO */
