#!/usr/bin/env python3
"""mklayout.py -- the layout ROM's four boards, as playfield tables.

Writes build/layoutpf.inc: `ORG` + `DB` lines that put HIT/MID/AUX tables for
four slots at the plane bytes the kernel reads (fuji_mailbox.h, the playfield
board), so the layout ROM shows composed boards with no cartridge work at all.
tools/pfcheck.py imports PICTURE from here to read a snapshot back against it.

The picture, per slot, is ten rows of ten characters: '.' sea, 'X' hit,
'O' miss, '#' hull (AUX), '+' cursor (AUX), 'H' a hit on a hull (HIT|MID|AUX).
"""

import sys

T_BASE, PLANE_LEN, ROW0, KLEN, KINDS, DIM = 0x1800, 0x80, 30, 20, 3, 10
HIT, MID, AUX = 0, 1, 2
CELL_H, RFLTA, RFLTB = 6, 3, 4

# The three glyphs the fleet strips use, from the cartridge's vcs_font.h: five
# rows of three ink bits, MSB leftmost. Clipped to its top three rows -- which
# is all PIPROW draws -- '#' is {5,7,5} and '=' is {0,7,0}.
FONT = {' ': (0, 0, 0, 0, 0), '#': (5, 7, 5, 7, 5), '=': (0, 7, 0, 7, 0)}

# One fleet per slot, in slot order: 0 top-left, 1 top-right, 2 bottom-left,
# 3 bottom-right. No two are the same and every one has both marks, so a
# strip drawn from the wrong slot or the wrong row is visible.
FLEET = ["###==", "#####", "#====", "##=#="]
REG_OF = [0, 0, 1, 1, 1, 1, 2, 2, 2, 2]
BITS_OF = [0x30, 0xC0, 0xC0, 0x30, 0x0C, 0x03, 0x03, 0x0C, 0x30, 0xC0]

# Slot 0 top-left, 1 top-right, 2 bottom-left, 3 bottom-right. Every kind
# appears in every slot, the corners are exercised, and no two slots are the
# same picture, so a half or a pair drawn from the wrong table is visible.
PICTURE = [
    [   # slot 0: an enemy board with the cursor at (4,3)
        "X.........",
        ".X....O...",
        "..X.......",
        "...X+.....",
        "....X.....",
        "O....X....",
        "......X...",
        ".......X..",
        "........X.",
        "O........X",
    ],
    [   # slot 1: misses and a sunk-looking cluster
        "O.O.O.O.O.",
        ".O.O.O.O.O",
        "..........",
        "...XXXX...",
        "..........",
        "..........",
        "OOO...XXXX",
        "..........",
        "..........",
        "X........O",
    ],
    [   # slot 2: YOUR board: hulls, one of them hit
        "#####.....",
        "..........",
        "..#......O",
        "..#..HH#..",
        "..#.......",
        "..#.......",
        ".....O....",
        "..........",
        ".......##.",
        "O........X",
    ],
    [   # slot 3: nearly empty
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        "..........",
        ".........X",
    ],
]


def kinds_of(ch):
    return {'.': (), 'X': (HIT, MID), 'O': (MID,), '#': (AUX,), '+': (AUX,),
            'H': (HIT, MID, AUX)}[ch]


def tables():
    """Return {plane offset: byte} for every table byte, all four slots."""
    out = {}
    for slot, pic in enumerate(PICTURE):
        half, pair = slot & 1, slot >> 1
        for kind in range(KINDS):
            for y in range(DIM):
                regs = [0, 0, 0]
                for x in range(DIM):
                    if kind in kinds_of(pic[y][x]):
                        regs[REG_OF[x]] |= BITS_OF[x]
                for r in range(3):
                    plane = r + 3 * half
                    off = plane * PLANE_LEN + ROW0 + kind * KLEN + pair * DIM + y
                    out[off] = regs[r]
    return out


def strips():
    """Return {plane offset: byte} for text rows 3 and 4, the fleet strips.

    A row is twelve columns across six planes, two columns to a plane byte:
    the even column in bits 7-5, the odd one in bits 3-1, the gap bits zero
    (firmware vcs_render.c, vcs_render_cell). Each slot gets six columns -- a
    leading space and five pips -- which is what GFSLOT composes.
    """
    out = {}
    for row, slots in ((RFLTA, (0, 1)), (RFLTB, (2, 3))):
        text = "".join(" " + FLEET[s] for s in slots)
        for col, ch in enumerate(text):
            g = FONT[ch]
            for line in range(CELL_H):
                ink = g[line] if line < len(g) else 0
                off = (col // 2) * PLANE_LEN + row * CELL_H + line
                out[off] = out.get(off, 0) | (ink << 1 if col & 1 else ink << 5)
    return out


def main():
    t = tables()
    st = strips()
    for plane in range(6):
        base = plane * PLANE_LEN + RFLTA * CELL_H
        print("        ORG     $%04X" % (T_BASE + base))
        row = [st.get(base + i, 0) for i in range(2 * CELL_H)]
        print("        DB      " + ",".join("$%02X" % b for b in row))
    print("; generated by tools/mklayout.py -- do not edit")
    for plane in range(6):
        base = plane * PLANE_LEN + ROW0
        print("        ORG     $%04X" % (T_BASE + base))
        row = [t.get(base + i, 0) for i in range(KINDS * KLEN)]
        for i in range(0, len(row), 20):
            print("        DB      " + ",".join("$%02X" % b for b in row[i:i+20]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
