#!/usr/bin/env python3
"""mktail.py -- export the fixed tail's addresses as assembler equates.

The fixed tail at $1F20-$1FFB is the only part of the window every bank sees
at the same address, so it is where shared code has to live. But the banks are
assembled separately, so they need those addresses as constants -- and a
hand-maintained list of them would be a list of numbers that go stale in
silence the moment a byte is added to any routine above them.

So the tail is assembled first and this reads the addresses back out of its
own listing. Nothing to keep in step by hand.

Usage: mktail.py cdtail.lst NAME[,NAME...] > tail.inc
"""

import re
import sys

# `  FNBEG :                      1F3A C |  FNPB :                  1F59 C |`
SYM = re.compile(r"\b([A-Z_][A-Z0-9_]*)\s*:\s*([0-9A-F]{4})\s+C\b")

TAIL_TOP = 0x1FFB               # FN_FIXED_TAIL's last usable byte

EMIT = re.compile(r"^\s*(?:\(\d+\)\s*)?\d+/([0-9A-Fa-f]{4})\s*:\s*"
                  r"((?:[0-9A-Fa-f]{2} )+)")


def tail_end(path):
    """One past the highest byte emitted below the vectors."""
    end = 0
    for line in open(path):
        m = EMIT.match(line)
        if not m:
            continue
        addr = int(m.group(1), 16)
        if addr >= 0x1FFC:              # the vectors are deliberate
            continue
        end = max(end, addr + len(m.group(2).split()))
    return end


def main():
    path, names = sys.argv[1], sys.argv[2].split(",")
    found = {}
    for line in open(path):
        for name, addr in SYM.findall(line):
            found.setdefault(name, int(addr, 16))

    missing = [n for n in names if n not in found]
    if missing:
        print("mktail: not in %s: %s" % (path, ", ".join(missing)),
              file=sys.stderr)
        return 1

    # The tail's overflow is silent and fatal: p2bin emits the whole
    # $1800-$1FFF range, so code running past $1FFB lands on the vectors and
    # the console resets into whatever the last instruction happened to be.
    #
    # The EMITTED extent is what matters, not the exported symbols -- the last
    # exported routine is not the last one assembled, and checking only the
    # symbols said "34 spare" for a tail that ran 32 bytes past the vectors.
    top = tail_end(path)
    if top > TAIL_TOP + 1:
        print("mktail: the tail reaches $%04X, past $%04X -- %d byte(s) over"
              % (top - 1, TAIL_TOP, top - 1 - TAIL_TOP), file=sys.stderr)
        return 1

    print("; generated by tools/mktail.py -- do not edit.")
    print("; The shared transport, assembled once into the fixed tail.")
    for n in names:
        print("%-8s EQU     $%04X" % (n, found[n]))
    print("; the tail reaches $%04X of $%04X (%d spare)"
          % (top - 1, TAIL_TOP, TAIL_TOP + 1 - top))
    return 0


if __name__ == "__main__":
    sys.exit(main())
