#!/usr/bin/env python3
# Build a pixel-outline TTF from the FujiNet Astrocade clients' 4x6 screen
# font (netcat's 96-glyph font.inc; the card games use the same art for
# 20H-5FH). Run under fontforge:
#   fontforge -lang=py -script make_screen_font.py <font.inc> <out.ttf>
#
# font.inc format (generated by netcat's tools/mkfont.py): after the
# FONT46: label, 96 glyphs x 6 DB rows, codepoints 20H-7FH, ink in the
# HIGH nibble, bit 7 leftmost. Column 3 is the inter-character gap and
# row 0 the inter-line gap, so the advance is the full 4-pixel cell.
# Descender tails live in row 5, so the baseline sits under row 4.
import re
import sys

import fontforge

inc_path, out_path = sys.argv[1], sys.argv[2]

rows = []
armed = False
for line in open(inc_path):
    if not armed:
        armed = line.strip().startswith("FONT46:")
        continue
    m = re.match(r"\s+DB\s+0?([0-9A-Fa-f]{1,2})H", line)
    if m:
        rows.append(int(m.group(1), 16))
if len(rows) != 96 * 6:
    sys.exit(f"expected {96*6} DB rows after FONT46:, found {len(rows)}")

PX = 170          # one pixel = 170 em units; the 4x6 cell is 680 x 1020
EM = 6 * PX

f = fontforge.font()
f.familyname = "Astrocade Screen"
f.fontname = "AstrocadeScreen"
f.fullname = "Astrocade Screen"
f.copyright = ("Glyph shapes from the FujiNet Astrocade clients' 4x6 "
               "screen font (netcat font.inc).")
f.em = EM
f.ascent = 5 * PX
f.descent = PX

for glyph in range(96):
    cp = 0x20 + glyph
    g = f.createChar(cp)
    pen = g.glyphPen()
    for r in range(6):
        byte = rows[glyph * 6 + r]
        for c in range(4):
            if byte & (0x80 >> c):
                x0 = c * PX
                y1 = 5 * PX - r * PX
                y0 = y1 - PX
                pen.moveTo((x0, y0))
                pen.lineTo((x0, y1))
                pen.lineTo((x0 + PX, y1))
                pen.lineTo((x0 + PX, y0))
                pen.closePath()
    pen = None
    g.width = 4 * PX
    g.removeOverlap()
    g.correctDirection()

f.selection.all()
f.generate(out_path)
print("wrote", out_path)
