#!/usr/bin/env bash
# build.sh -- assemble the Atari 2600 Battleship client.
#
#   ./build.sh            the client:    build/battleship.bin, 16384 bytes
#   ./build.sh layout     the screen with no network: build/layout.bin
#
# The client is (N+1) x 2048 bytes: N 2K banks then the 2K fixed half, which
# is the layout vcs_set_image expects. MAME's vcs_cart_slot_device::call_load()
# accepts only 4096/8192/16384/32768, so N is 1, 3, 7 or 15 and nothing
# between. Six banks are needed; the seventh is a stub back to bank 0.
#
# The "FUJI" claim is stamped into the fixed half. Without it the cartridge
# treats the image as a game and the mailbox goes dead the moment it boots.
#
# Env:
#   ENDPOINT=...       the server (default https://battleship.carr-designs.com/)
#   FUJI_FIRMWARE=...  firmware tree (default ~/Workspace/fujinet-firmware)

set -euo pipefail
cd "$(dirname "$0")"

FUJI_FIRMWARE="${FUJI_FIRMWARE:-$HOME/Workspace/fujinet-firmware}"
VCS="$FUJI_FIRMWARE/pico/atari-2600"

if command -v asl >/dev/null 2>&1; then
    AS=asl P2BIN=p2bin
elif [ -x "$HOME/asl/asl" ]; then
    AS="$HOME/asl/asl" P2BIN="$HOME/asl/p2bin"
else
    echo "build.sh: no Macroassembler AS found (tried PATH and ~/asl)" >&2
    exit 1
fi

mkdir -p build

# The equates are hand-mirrored from the firmware header, so check them BEFORE
# assembling anything: a drifted address assembles cleanly, runs, draws a
# screen, and silently talks to a page that decodes nothing.
#
# The blit, playfield and path equates are passed with --extra rather than
# living in that tool's shared table: a name listed there and missing from a
# client's .inc is a failure, so the table can only hold what EVERY client
# has. The appkey command bytes are FUJI device ids from fujiCommandID.h, not
# the mailbox header, so they are not listed.
python3 "$VCS/tools/checkdefs.py" \
    "$VCS/firmware/include/fuji_mailbox.h" src/fujinet.inc \
    --extra "FB_TCELL=FN_BLIT_TCELL,FB_PATH=FN_BLIT_PATH,FB_TEXT=FN_BLIT_TEXT,FB_PFCLR=FN_BLIT_PFCLR,FB_PFLD=FN_BLIT_PFIELD,FB_PFHUL=FN_BLIT_PFHULL,FB_PFCEL=FN_BLIT_PFCELL,PFROW0=FN_PF_ROW0,PFKLEN=FN_PF_KIND_LEN,PFM_HIT=FN_PFM_HIT,PFM_MID=FN_PFM_MID,PFM_AUX=FN_PFM_AUX,PFM_ALL=FN_PFM_ALL,PFM_CLR=FN_PFM_CLEAR,PFSLOTS=FN_PF_SLOTS,FNBGEN=FN_B_BLITGEN,FH_BSL=FN_HOT_BLIT_SL,FH_BSH=FN_HOT_BLIT_SH,FH_BDL=FN_HOT_BLIT_DL,FH_BDH=FN_HOT_BLIT_DH,FH_BCNT=FN_HOT_BLIT_CNT,FH_BGO=FN_HOT_BLIT_GO,FP_POPCH=FN_PATH_POPCH,FP_SEL0=FN_PATH_SEL0,FP_SEL1=FN_PATH_SEL1,FP_SEL3=FN_PATH_SEL3,FP_SEED=FN_PATH_SEED,FP_COMMIT=FN_PATH_COMMIT,FNTROW=FN_T_ROWS,FNTCLH=FN_T_CELL_H"

# Regenerated every run, so a stale value cannot survive an environment
# change.
{
    echo "; generated by build.sh -- do not edit"
    printf 'UENDPT: DB      "%s"\n' \
        "${ENDPOINT:-https://battleship.carr-designs.com/}"
    echo "        DB      0"
} > build/endpoint.inc

# p2bin ALWAYS emits its full -r range, so an over-long bank is truncated in
# SILENCE: the image builds, the size is right, checkrom passes, and the
# instructions past $17FF are simply gone. The assembler's own listing is the
# only thing that knows, so the build asks it.
bankfits() {
    python3 tools/checkbanks.py "build/$1.lst" "$2" "$1"
}

assemble() {
    local b=$1
    ( cd src && "$AS" -q -L -i . "$b.asm" )
    mv "src/$b.p" "build/$b.p"
    mv -f "src/$b.lst" "build/$b.lst" 2>/dev/null || true
}

stampclaim() {
    # The fixed half is the LAST 2K, so the claim's offset is
    # (size - 2048) + (FN_R_CLAIM - $1800).
    local f=$1 size
    size=$(stat -c%s "$f")
    printf 'FUJI' | dd of="$f" bs=1 \
        seek=$((size - 0x800 + 0x0710)) conv=notrunc status=none
    echo "$f: $size bytes"
}

# ---------------- the layout ROM: one flat 4K image ----------------
if [ "${1:-}" = "layout" ]; then
    # The baked tables and the baked fleet strips, from the picture in
    # tools/mklayout.py. Generated here and not by hand: build/ is ignored, so
    # a stale copy is the normal state of a fresh tree, and a stale one fails
    # tools/pfcheck.py somewhere that looks like the kernel's fault.
    python3 tools/mklayout.py > build/layoutpf.inc
    assemble layout
    bankfits layout $((0x1800))
    "$P2BIN" build/layout.p build/layout.bin -r '$1000-$1FFF' -l 0
    rm -f build/layout.p
    stampclaim build/layout.bin
    python3 "$VCS/tools/checkrom.py" build/layout.bin
    exit 0
fi

# ---------------- the client: seven banks and the fixed half ----------------
BANKS="bslobby bsgame bsnet bsmenu bsname bsplace bscomp"

# THE TAIL IS ASSEMBLED FIRST: it holds the shared transport, and the banks
# reach it through build/tail.inc, generated from the addresses the tail
# actually assembled to. Nothing keeps a list of those by hand.
assemble bstail
python3 tools/mktail.py build/bstail.lst \
    FNRW,FNARM,FNCHK,FNBEG,FNPB,FNPW,FNGO,FNACK,\
FNROWA,FNCHR,FNENDR,FNSPC > build/tail.inc
cat build/tail.inc | tail -1 | sed 's/^; */  tail: /'

parts=()
for b in $BANKS; do
    assemble "$b"
    bankfits "$b" $((0x1800))
    "$P2BIN" "build/$b.p" "build/$b.bin" -r '$1000-$17FF' -l 0
    rm -f "build/$b.p"
    parts+=("build/$b.bin")
done

"$P2BIN" build/bstail.p build/bstail.bin -r '$1800-$1FFF' -l 0
rm -f build/bstail.p

cat "${parts[@]}" build/bstail.bin > build/battleship.bin
rm -f "${parts[@]}" build/bstail.bin

stampclaim build/battleship.bin
python3 "$VCS/tools/checkrom.py" build/battleship.bin
