#import "../lib.typ": *
#set heading(numbering: "A.1")
= Program Listings

The library, this handbook's additions, and the example programs, as built and run. The Battleship sources are in Appendix D.

#listing2("listings/common/fujinet.inc", "listings/common/fujinet.inc")
#listing2("listings/common/fujilib.inc", "listings/common/fujilib.inc")
#listing2("listings/common/fujidisp.inc", "listings/common/fujidisp.inc")
#listing2("listings/common/vcs.inc", "listings/common/vcs.inc")
#listing2("listings/common/netdefs.inc", "listings/common/netdefs.inc")
#listing2("listings/common/devdefs.inc", "listings/common/devdefs.inc")
#listing2("listings/asm/hello.asm", "listings/asm/hello.asm")
#listing2("listings/asm/fujitest.asm", "listings/asm/fujitest.asm")
#listing2("listings/asm/netget.asm", "listings/asm/netget.asm")
#listing2("listings/asm/fujidir.asm", "listings/asm/fujidir.asm")
#listing2("listings/asm/fujiboot.asm", "listings/asm/fujiboot.asm")
#listing2("listings/asm/appkey.asm", "listings/asm/appkey.asm")
#listing2("listings/asm/clock.asm", "listings/asm/clock.asm")
#listing2("listings/asm/build.sh", "listings/asm/build.sh")
#listing2("listings/dasm/fujibas.h", "listings/dasm/fujibas.h")
#listing2("listings/bas/fujitail.asm", "listings/bas/fujitail.asm")
#listing2("listings/bas/fujitext.asm", "listings/bas/fujitext.asm")
#listing2("listings/bas/fujiconst.bas (generated)", "listings/bas/fujiconst.bas")
#listing2("listings/bas/hello.bas", "listings/bas/hello.bas")
#listing2("listings/bas/arm.bas", "listings/bas/arm.bas")
#listing2("listings/bas/text.bas", "listings/bas/text.bas")
#listing2("listings/bas/netget.bas", "listings/bas/netget.bas")
#listing2("listings/bas/dir.bas", "listings/bas/dir.bas")
#listing2("listings/bas/boot.bas", "listings/bas/boot.bas")
#listing2("listings/bas/appkey.bas", "listings/bas/appkey.bas")
#listing2("listings/bas/clock.bas", "listings/bas/clock.bas")
#listing2("listings/bas/build.sh", "listings/bas/build.sh")
#listing2("tools/bbfix.py", "tools/bbfix.py")
#listing2("tools/as2dasm.py", "tools/as2dasm.py")
#listing2("tools/mkfujiconst.py", "tools/mkfujiconst.py")
#listing2("emu/run.sh", "emu/run.sh")
#listing2("emu/txn.lua", "emu/txn.lua")
#listing2("emu/text.lua", "emu/text.lua")
#listing2("emu/frames.lua", "emu/frames.lua")
