#!/usr/bin/env bash
# build.sh -- assemble the handbook's assembly clients with Macroassembler AS.
#
#   ./build.sh [client ...]        default: every client here
#
# Output: build/<client>.bin, exactly 4096 bytes -- one 2K bank plus the fixed
# half -- with the "FUJI" claim stamped in and tools/checkrom.py run over it.
# The library (../common) is the cartridge bring-up's testrom, verbatim; its
# equates are checked against the firmware header before anything assembles,
# because a drifted address assembles cleanly, runs, draws a screen, and
# silently talks to a page that decodes nothing.
set -euo pipefail
cd "$(dirname "$0")"
FN2600="${FN2600:-$HOME/Workspace/fn-2600/pico/atari-2600}"
if command -v asl >/dev/null 2>&1; then AS=asl P2BIN=p2bin
elif [ -x "$HOME/asl/asl" ]; then AS="$HOME/asl/asl" P2BIN="$HOME/asl/p2bin"
else echo "build.sh: no Macroassembler AS found (tried PATH and ~/asl)" >&2; exit 1; fi
mkdir -p build
python3 "$FN2600/tools/checkdefs.py" "$FN2600/firmware/include/fuji_mailbox.h" ../common/fujinet.inc

claim_off() { echo $(( $1 - 0x800 + 0x0710 )); }
build_one() {
    local name=$1
    if [ "$name" = hello ]; then
        python3 "$FN2600/tools/vcsfont.py" --screen-file screen.txt > screen.inc
    fi
    if [ "$name" = fujiboot ]; then
        { echo "; generated by build.sh -- do not edit"
          echo "BOOTHST EQU     ${BOOT_HOST:-0}"
          printf 'BOOTPTH:DB      "%s"\n' "${BOOT_PATH:-/vcsgame.bin}"
          echo "        DB      0"; } > bootcfg.inc
    fi
    $AS -q -L -i ../common "$name.asm"
    mv "$name.p" "build/$name.p"
    mv -f "$name.lst" "build/$name.lst" 2>/dev/null || true
    $P2BIN "build/$name.p" "build/$name.bin" -r '$1000-$1FFF' -l 0
    rm -f "build/$name.p"
    local size; size=$(stat -c%s "build/$name.bin")
    printf 'FUJI' | dd of="build/$name.bin" bs=1 seek="$(claim_off "$size")" conv=notrunc status=none
    python3 "$FN2600/tools/checkrom.py" "build/$name.bin"
    echo "build/$name.bin: $size bytes"
}
clients=("$@")
[ ${#clients[@]} -eq 0 ] && clients=(hello fujitest fujiboot fujidir netget)
for c in "${clients[@]}"; do build_one "$c"; done
