#ifndef UDG_H
#define UDG_H

/**
 * @brief 5 Card Stud UDGs for TMS9918 GRAPHICS II
 * @verbose GENERATED by support/tms9918/convert-tiles.py from the MS-DOS
 *          CGA tiles in src/msdos/charset.h - do not edit by hand.
 *          1 bit per pixel; ink and paper colors are applied per cell
 *          at draw time by the platform's graphics.c.
 */

#define UDG_CARD_TL 0x80
#define UDG_CARD_BL 0x81
#define UDG_CARD_TOP 0x82
#define UDG_CARD_BOT 0x83
#define UDG_CARD_TOP_TRIM 0x84
#define UDG_CARD_BOT_TRIM 0x85
#define UDG_CARD_VERT 0x86
#define UDG_CARD_BR_STUB 0x96
#define UDG_CARD_TR_STUB 0x97
#define UDG_BACK_RCOL_TOP 0x9B
#define UDG_BACK_RCOL_MID 0x9C
#define UDG_BACK_RCOL_BOT 0x9D
#define UDG_BACK_L_TOP 0x9E
#define UDG_BACK_R_TOP 0x9F
#define UDG_BACK_L_MID 0xA0
#define UDG_BACK_R_MID 0xA1
#define UDG_BACK_L_BOT 0xA2
#define UDG_BACK_R_BOT 0xA3
#define UDG_BOX_TL 0xA4
#define UDG_BOX_TR 0xA5
#define UDG_BOX_H 0xA6
#define UDG_BOX_BL 0xA7
#define UDG_BOX_BR 0xA8
#define UDG_BOX_V 0xA9
#define UDG_RANK_2 0xAA
#define UDG_RANK_3 0xAB
#define UDG_RANK_4 0xAC
#define UDG_RANK_5 0xAD
#define UDG_RANK_6 0xAE
#define UDG_RANK_7 0xAF
#define UDG_RANK_8 0xB0
#define UDG_RANK_9 0xB1
#define UDG_RANK_T 0xB2
#define UDG_RANK_J 0xB3
#define UDG_RANK_Q 0xB4
#define UDG_RANK_K 0xB5
#define UDG_RANK_A 0xB6
#define UDG_SUIT_SPADE 0xB7
#define UDG_SUIT_CLUB 0xB8
#define UDG_SUIT_DIAMOND 0xB9
#define UDG_SUIT_HEART 0xBA
#define UDG_CHIP 0xBC
#define UDG_HIDDEN_L 0xBF
#define UDG_HIDDEN_R 0xC0
#define UDG_SCREEN_TL 0xC1
#define UDG_SCREEN_TR 0xC2
#define UDG_SCREEN_BL 0xC3
#define UDG_SCREEN_BR 0xC4

static const char udg[] =
{
    /* 0x80 UDG_CARD_TL (card_edges[0])
       card top-left corner
       ........
       ........
       ........
       ........
       ........
       ........
       ..XXXXXX
       XXXXXXXX
    */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3F, 0xFF,

    /* 0x81 UDG_CARD_BL (card_edges[1])
       card bottom-left corner
       XXXXXXXX
       ..XXXXXX
       ........
       ........
       ........
       ........
       ........
       ........
    */
    0xFF, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x82 UDG_CARD_TOP (card_edges[2])
       card top edge
       ........
       ........
       ........
       ........
       ........
       ........
       XXXXXXXX
       XXXXXXXX
    */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF,

    /* 0x83 UDG_CARD_BOT (card_edges[3])
       card bottom edge
       XXXXXXXX
       XXXXXXXX
       ........
       ........
       ........
       ........
       ........
       ........
    */
    0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x84 UDG_CARD_TOP_TRIM (card_edges[4])
       top edge, right px trimmed
       ........
       ........
       ........
       ........
       ........
       ........
       ..XXXXX.
       XXXXXXXX
    */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3E, 0xFF,

    /* 0x85 UDG_CARD_BOT_TRIM (card_edges[5])
       bottom edge, right px trimmed
       XXXXXXXX
       ..XXXXX.
       ........
       ........
       ........
       ........
       ........
       ........
    */
    0xFF, 0x3E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x86 UDG_CARD_VERT (card_edges[6])
       vertical rule (= card_bits[0])
       XX......
       XX......
       XX......
       XX......
       XX......
       XX......
       XX......
       XX......
    */
    0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0, 0xC0,

    /* 0x87 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x88 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x89 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x8A unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x8B unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x8C unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x8D unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x8E unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x8F unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x90 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x91 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x92 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x93 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x94 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x95 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x96 UDG_CARD_BR_STUB (card_edges[7])
       bottom-right joint
       XX......
       ........
       ........
       ........
       ........
       ........
       ........
       ........
    */
    0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x97 UDG_CARD_TR_STUB (card_edges[8])
       top-right joint
       ........
       ........
       ........
       ........
       ........
       ........
       ........
       XX......
    */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xC0,

    /* 0x98 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x99 unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x9A unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0x9B UDG_BACK_RCOL_TOP (card_bits[1])
       partial-right back, top
       XX......
       XXX.XX..
       XX.XX.X.
       XXXX.XX.
       XXX.XX..
       XX.XX.X.
       XXXX.XX.
       XXX.XX..
    */
    0xC0, 0xEC, 0xDA, 0xF6, 0xEC, 0xDA, 0xF6, 0xEC,

    /* 0x9C UDG_BACK_RCOL_MID (card_bits[2])
       partial-right back, middle
       XXX.XX..
       XXXX.XX.
       XX.XX.X.
       XXX.XX..
       XXXX.XX.
       XX.XX.X.
       XXX.XX..
       XXXX.XX.
    */
    0xEC, 0xF6, 0xDA, 0xEC, 0xF6, 0xDA, 0xEC, 0xF6,

    /* 0x9D UDG_BACK_RCOL_BOT (card_bits[3])
       partial-right back, bottom
       XXXX.XX.
       XXX.XX..
       XX.XX.X.
       XXXX.XX.
       XXX.XX..
       XX.XX.X.
       XXXX.XX.
       XX......
    */
    0xF6, 0xEC, 0xDA, 0xF6, 0xEC, 0xDA, 0xF6, 0xC0,

    /* 0x9E UDG_BACK_L_TOP (card_bits[6])
       back hatch left col, top
       XX......
       XX.X.XX.
       XX.XX.XX
       XX..XX.X
       XX.X.XX.
       XX.XX.XX
       XX..XX.X
       XX.X.XX.
    */
    0xC0, 0xD6, 0xDB, 0xCD, 0xD6, 0xDB, 0xCD, 0xD6,

    /* 0x9F UDG_BACK_R_TOP (card_bits[7])
       back hatch right col, top
       ........
       .XX.XX..
       XX.XX.X.
       X.XX.XX.
       .XX.XX..
       XX.XX.X.
       X.XX.XX.
       .XX.XX..
    */
    0x00, 0x6C, 0xDA, 0xB6, 0x6C, 0xDA, 0xB6, 0x6C,

    /* 0xA0 UDG_BACK_L_MID (card_bits[8])
       back hatch left col, middle
       XX.X.XX.
       XX..XX.X
       XX.XX.XX
       XX.X.XX.
       XX..XX.X
       XX.XX.XX
       XX.X.XX.
       XX..XX.X
    */
    0xD6, 0xCD, 0xDB, 0xD6, 0xCD, 0xDB, 0xD6, 0xCD,

    /* 0xA1 UDG_BACK_R_MID (card_bits[9])
       back hatch right col, middle
       .XX.XX..
       X.XX.XX.
       XX.XX.X.
       .XX.XX..
       X.XX.XX.
       XX.XX.X.
       .XX.XX..
       X.XX.XX.
    */
    0x6C, 0xB6, 0xDA, 0x6C, 0xB6, 0xDA, 0x6C, 0xB6,

    /* 0xA2 UDG_BACK_L_BOT (card_bits[10])
       back hatch left col, bottom
       XX..XX.X
       XX.X.XX.
       XX.XX.XX
       XX..XX.X
       XX.X.XX.
       XX.XX.XX
       XX..XX.X
       XX......
    */
    0xCD, 0xD6, 0xDB, 0xCD, 0xD6, 0xDB, 0xCD, 0xC0,

    /* 0xA3 UDG_BACK_R_BOT (card_bits[11])
       back hatch right col, bottom
       X.XX.XX.
       .XX.XX..
       XX.XX.X.
       X.XX.XX.
       .XX.XX..
       XX.XX.X.
       X.XX.XX.
       ........
    */
    0xB6, 0x6C, 0xDA, 0xB6, 0x6C, 0xDA, 0xB6, 0x00,

    /* 0xA4 UDG_BOX_TL (pot_border[0])
       box top-left
       ........
       ........
       ........
       ......XX
       .....XXX
       ....XXX.
       ...XXX..
       ...XX...
    */
    0x00, 0x00, 0x00, 0x03, 0x07, 0x0E, 0x1C, 0x18,

    /* 0xA5 UDG_BOX_TR (pot_border[2])
       box top-right
       ........
       ........
       ........
       XX......
       XXX.....
       .XXX....
       ..XXX...
       ...XX...
    */
    0x00, 0x00, 0x00, 0xC0, 0xE0, 0x70, 0x38, 0x18,

    /* 0xA6 UDG_BOX_H (pot_border[1])
       box horizontal
       ........
       ........
       ........
       XXXXXXXX
       XXXXXXXX
       ........
       ........
       ........
    */
    0x00, 0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0x00,

    /* 0xA7 UDG_BOX_BL (pot_border[3])
       box bottom-left
       ...XX...
       ...XXX..
       ....XXX.
       .....XXX
       ......XX
       ........
       ........
       ........
    */
    0x18, 0x1C, 0x0E, 0x07, 0x03, 0x00, 0x00, 0x00,

    /* 0xA8 UDG_BOX_BR (pot_border[4])
       box bottom-right
       ...XX...
       ..XXX...
       .XXX....
       XXX.....
       XX......
       ........
       ........
       ........
    */
    0x18, 0x38, 0x70, 0xE0, 0xC0, 0x00, 0x00, 0x00,

    /* 0xA9 UDG_BOX_V (pot_border[5])
       box vertical
       ...XX...
       ...XX...
       ...XX...
       ...XX...
       ...XX...
       ...XX...
       ...XX...
       ...XX...
    */
    0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18,

    /* 0xAA UDG_RANK_2 (black_card_front[1])
       rank 2
       ........
       ..XXX...
       .X...X..
       .....X..
       ....X...
       ...X....
       ..X.....
       .XXXXX..
    */
    0x00, 0x38, 0x44, 0x04, 0x08, 0x10, 0x20, 0x7C,

    /* 0xAB UDG_RANK_3 (black_card_front[2])
       rank 3
       ........
       ..XXX...
       .X...X..
       .....X..
       ...XX...
       .....X..
       .X...X..
       ..XXX...
    */
    0x00, 0x38, 0x44, 0x04, 0x18, 0x04, 0x44, 0x38,

    /* 0xAC UDG_RANK_4 (black_card_front[3])
       rank 4
       ........
       ....X...
       ...XX...
       ..X.X...
       .X..X...
       .XXXXX..
       ....X...
       ....X...
    */
    0x00, 0x08, 0x18, 0x28, 0x48, 0x7C, 0x08, 0x08,

    /* 0xAD UDG_RANK_5 (black_card_front[4])
       rank 5
       ........
       .XXXXX..
       .X......
       .XXXX...
       .....X..
       .....X..
       .X...X..
       ..XXX...
    */
    0x00, 0x7C, 0x40, 0x78, 0x04, 0x04, 0x44, 0x38,

    /* 0xAE UDG_RANK_6 (black_card_front[5])
       rank 6
       ........
       ...XX...
       ..X.....
       .X......
       .XXXX...
       .X...X..
       .X...X..
       ..XXX...
    */
    0x00, 0x18, 0x20, 0x40, 0x78, 0x44, 0x44, 0x38,

    /* 0xAF UDG_RANK_7 (black_card_front[6])
       rank 7
       ........
       .XXXXX..
       .....X..
       ....X...
       ...X....
       ..X.....
       ..X.....
       ..X.....
    */
    0x00, 0x7C, 0x04, 0x08, 0x10, 0x20, 0x20, 0x20,

    /* 0xB0 UDG_RANK_8 (black_card_front[7])
       rank 8
       ........
       ..XXX...
       .X...X..
       .X...X..
       ..XXX...
       .X...X..
       .X...X..
       ..XXX...
    */
    0x00, 0x38, 0x44, 0x44, 0x38, 0x44, 0x44, 0x38,

    /* 0xB1 UDG_RANK_9 (black_card_front[8])
       rank 9
       ........
       ..XXX...
       .X...X..
       .X...X..
       ..XXXX..
       .....X..
       ....X...
       ..XX....
    */
    0x00, 0x38, 0x44, 0x44, 0x3C, 0x04, 0x08, 0x30,

    /* 0xB2 UDG_RANK_T (black_card_front[9])
       rank T
       ........
       .X..XX..
       XX.X..X.
       .X.X..X.
       .X.X..X.
       .X.X..X.
       .X.X..X.
       .X..XX..
    */
    0x00, 0x4C, 0xD2, 0x52, 0x52, 0x52, 0x52, 0x4C,

    /* 0xB3 UDG_RANK_J (black_card_front[10])
       rank J
       ........
       .....X..
       .....X..
       .....X..
       .....X..
       .....X..
       .X...X..
       ..XXX...
    */
    0x00, 0x04, 0x04, 0x04, 0x04, 0x04, 0x44, 0x38,

    /* 0xB4 UDG_RANK_Q (black_card_front[11])
       rank Q
       ........
       ..XXX...
       .X...X..
       .X...X..
       .X...X..
       .X.X.X..
       .X..X...
       ..XX.X..
    */
    0x00, 0x38, 0x44, 0x44, 0x44, 0x54, 0x48, 0x34,

    /* 0xB5 UDG_RANK_K (black_card_front[12])
       rank K
       ........
       .X...X..
       .X..X...
       .X.X....
       .XX.....
       .X.X....
       .X..X...
       .X...X..
    */
    0x00, 0x44, 0x48, 0x50, 0x60, 0x50, 0x48, 0x44,

    /* 0xB6 UDG_RANK_A (black_card_front[13])
       rank A
       ........
       ...XXX..
       ..X...X.
       ..X...X.
       ..XXXXX.
       ..X...X.
       ..X...X.
       ..X...X.
    */
    0x00, 0x1C, 0x22, 0x22, 0x3E, 0x22, 0x22, 0x22,

    /* 0xB7 UDG_SUIT_SPADE (black_card_front[14])
       spade
       ...X....
       ..XXX...
       .XXXXX..
       XXXXXXX.
       XXX.XXX.
       ...X....
       .XXXXX..
       ........
    */
    0x10, 0x38, 0x7C, 0xFE, 0xEE, 0x10, 0x7C, 0x00,

    /* 0xB8 UDG_SUIT_CLUB (black_card_front[15])
       club
       ..XXX...
       ..XXX...
       XX.X.XX.
       XXXXXXX.
       XXX.XXX.
       ...X....
       .XXXXX..
       ........
    */
    0x38, 0x38, 0xD6, 0xFE, 0xEE, 0x10, 0x7C, 0x00,

    /* 0xB9 UDG_SUIT_DIAMOND (red_card_front[14])
       diamond
       ...X....
       ..XXX...
       .XXXXX..
       XXXXXXX.
       .XXXXX..
       ..XXX...
       ...X....
       ........
    */
    0x10, 0x38, 0x7C, 0xFE, 0x7C, 0x38, 0x10, 0x00,

    /* 0xBA UDG_SUIT_HEART (red_card_front[15])
       heart
       ........
       .XX.XX..
       XXXXXXX.
       XXXXXXX.
       .XXXXX..
       ..XXX...
       ...X....
       ........
    */
    0x00, 0x6C, 0xFE, 0xFE, 0x7C, 0x38, 0x10, 0x00,

    /* 0xBB unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0xBC UDG_CHIP (chip[0])
       pot chip (white X becomes cutout)
       ........
       ..XXXX..
       .X.XX.X.
       .XX..XX.
       .XX..XX.
       .X.XX.X.
       ..XXXX..
       ........
    */
    0x00, 0x3C, 0x5A, 0x66, 0x66, 0x5A, 0x3C, 0x00,

    /* 0xBD unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0xBE unused */
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,

    /* 0xBF UDG_HIDDEN_L (card_bits[12])
       hole-card marker, left
       XX......
       XXXXXXXX
       XX.XX.XX
       XX..XX.X
       XX.X.XX.
       XX.XX.XX
       XXXXXXXX
       XX......
    */
    0xC0, 0xFF, 0xDB, 0xCD, 0xD6, 0xDB, 0xFF, 0xC0,

    /* 0xC0 UDG_HIDDEN_R (card_bits[13])
       hole-card marker, right
       ........
       XXXXXXXX
       XX.XX.X.
       X.XX.XX.
       .XX.XX..
       XX.XX.X.
       XXXXXXXX
       ........
    */
    0x00, 0xFF, 0xDA, 0xB6, 0x6C, 0xDA, 0xFF, 0x00,

    /* 0xC1 UDG_SCREEN_TL (border[0])
       screen corner top-left
       ....XXXX
       ..XXXXXX
       .XXXXXXX
       .XXXXXXX
       XXXXXXXX
       XXXXXXXX
       XXXXXXXX
       XXXXXXXX
    */
    0x0F, 0x3F, 0x7F, 0x7F, 0xFF, 0xFF, 0xFF, 0xFF,

    /* 0xC2 UDG_SCREEN_TR (border[1])
       screen corner top-right
       XXXX....
       XXXXXX..
       XXXXXXX.
       XXXXXXX.
       XXXXXXXX
       XXXXXXXX
       XXXXXXXX
       XXXXXXXX
    */
    0xF0, 0xFC, 0xFE, 0xFE, 0xFF, 0xFF, 0xFF, 0xFF,

    /* 0xC3 UDG_SCREEN_BL (border[2])
       screen corner bottom-left
       XXXXXXXX
       XXXXXXXX
       XXXXXXXX
       XXXXXXXX
       .XXXXXXX
       .XXXXXXX
       ..XXXXXX
       ....XXXX
    */
    0xFF, 0xFF, 0xFF, 0xFF, 0x7F, 0x7F, 0x3F, 0x0F,

    /* 0xC4 UDG_SCREEN_BR (border[3])
       screen corner bottom-right
       XXXXXXXX
       XXXXXXXX
       XXXXXXXX
       XXXXXXXX
       XXXXXXX.
       XXXXXXX.
       XXXXXX..
       XXXX....
    */
    0xFF, 0xFF, 0xFF, 0xFF, 0xFE, 0xFE, 0xFC, 0xF0,
};

#endif /* UDG_H */
