#!/usr/bin/env python3
"""as2dasm.py -- translate the Macroassembler AS client sources to dasm.

The cartridge bring-up's client library (testrom/fujinet.inc, fujilib.inc,
fujidisp.inc, vcs.inc) is written for Macroassembler AS. batari Basic
programs go through dasm, so the library has to exist in dasm syntax too --
and two hand-maintained copies of a transport drift. This translates the AS
sources mechanically; the dasm twin in listings/dasm/ is GENERATED and the
build diffs it against the committed copy.

    as2dasm.py <in.inc|in.asm> <out>

Rules (all the AS constructs the client sources use):
  LABEL:            -> LABEL             (dasm labels take no colon)
  DB / DW           -> .byte / .word
  REPT n .. ENDM    -> REPEAT n .. REPEND
  lsr a (asl/rol/ror) -> lsr              (implied accumulator)
  (SYM)&$FF / (SYM)>>8 -> <SYM / >SYM     (low / high byte)
  (expr)&$FF        -> [expr]&$FF        (dasm groups with brackets)
  'c'               -> 'c                (dasm character constant)
  CPU 6502          -> processor 6502
  INCLUDE "x.inc"   -> include "x.h" / "x.asm" (the dasm twins' names)
  END               -> dropped
The zero-page equates of fujinet.inc are wrapped in IFNCONST so a batari
Basic program can place them on cells of its own choosing before including
the header (bB's kernel owns $80-$A3, where the AS clients keep theirs).
"""
import re
import sys

ZP_CELLS = {"FNSEQ", "FNCNT", "FNDEV", "FNCMD", "FNNPR", "FNTMO",
            "FNPTRL", "FNPTRH", "FNPCNT", "INCUR", "INPREV",
            "PAD3", "SAVSP"}
INC_MAP = {"vcs.inc": "vcs2600.h", "fujinet.inc": "fujinet.h",
           "fujilib.inc": "fujilib.asm", "fujidisp.inc": "fujidisp.asm",
           "screen.inc": "screen.asm", "bootcfg.inc": "bootcfg.asm"}


def split_comment(line):
    """Split at the first ';' that is not inside a double-quoted string."""
    inq = False
    for i, ch in enumerate(line):
        if ch == '"':
            inq = not inq
        elif ch == ';' and not inq:
            return line[:i], line[i:]
    return line, ""


def xlate(line):
    code, comment = split_comment(line.rstrip("\n"))
    if not code.strip():
        return code + comment
    m = re.match(r"^\s*(CPU)\s+\S+", code, re.I)
    if m:
        return "        processor 6502" + comment
    if re.match(r"^\s*END\s*$", code, re.I):
        return ";" + code + comment
    m = re.match(r'^(\s*)INCLUDE\s+"([^"]+)"', code, re.I)
    if m:
        name = m.group(2)
        return '%sinclude "%s"' % (m.group(1), INC_MAP.get(name, name)) + comment
    # label: -> label
    code = re.sub(r"^([A-Za-z_][A-Za-z0-9_]*):", r"\1", code)
    # directives
    code = re.sub(r"(^|\s)DB(\s)", r"\1.byte\2", code)
    code = re.sub(r"(^|\s)DW(\s)", r"\1.word\2", code)
    code = re.sub(r"(^|\s)REPT(\s)", r"\1REPEAT\2", code)
    code = re.sub(r"(^|\s)ENDM\s*$", r"\1REPEND", code)
    # implied accumulator
    code = re.sub(r"\b(asl|lsr|rol|ror)\s+a\b", r"\1", code, flags=re.I)
    # low / high byte of a symbol
    code = re.sub(r"\(([A-Za-z_][A-Za-z0-9_]*)\)&\$FF", r"<\1", code)
    code = re.sub(r"\(([A-Za-z_][A-Za-z0-9_]*)\)>>8", r">\1", code)
    # (expr)&$FF -> [expr]&$FF
    code = re.sub(r"\(([^()]+)\)&\$FF", r"[\1]&$FF", code)
    # character constants
    code = re.sub(r"'(.)'", r"'\1", code)
    return code + comment


def main():
    src, dst = sys.argv[1], sys.argv[2]
    out = ["; GENERATED by tools/as2dasm.py from %s -- do not edit; edit the AS"
           % src.split("/")[-1],
           "; source and regenerate. dasm syntax; see the translator for the rules."]
    for line in open(src):
        t = xlate(line)
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s+EQU\s+", t)
        if m and m.group(1) in ZP_CELLS:
            out.append("        IFNCONST %s" % m.group(1))
            out.append(t)
            out.append("        ENDIF")
        else:
            out.append(t)
    open(dst, "w").write("\n".join(out) + "\n")
    print("wrote", dst)


if __name__ == "__main__":
    main()
