#!/usr/bin/env python3
"""mkfujiconst.py -- the BASIC half of the mailbox header.

batari Basic emits a name it does not know as a MEMORY reference: `x = FNDEVF`
becomes `LDA FNDEVF`, a load from address $70, not the constant. A value has
to be declared to the compiler with `const`. This generates that block from
the dasm headers (fujinet.h, fujibas.h): every plain numeric equate that is a
VALUE -- device ids, command ids, register numbers, hotspot offsets, blit
kinds, path ops, error codes -- and none that is an ADDRESS (the window at
$1xxx, the zero-page cells), which BASIC must keep treating as memory.
listings/bas/build.sh prepends the result to every program it compiles.

    mkfujiconst.py fujinet.h fujibas.h > fujiconst.bas
"""
import re
import sys

ZP = {"FNSEQ", "FNCNT", "FNDEV", "FNCMD", "FNNPR", "FNTMO", "FNPTRL",
      "FNPTRH", "FNPCNT", "INCUR", "INPREV", "PAD3", "SAVSP"}
out = [" rem fujiconst.bas -- GENERATED by tools/mkfujiconst.py from the dasm",
       " rem headers; prepended to every program by build.sh. Do not edit."]
seen = set()
for path in sys.argv[1:]:
    for line in open(path):
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s+(?:EQU|=)\s+(\$[0-9A-Fa-f]+|\d+)\b", line)
        if not m:
            continue
        name, val = m.group(1), m.group(2)
        n = int(val[1:], 16) if val.startswith("$") else int(val)
        if name in ZP or name in seen or n >= 0x1000:
            continue
        seen.add(name)
        out.append(" const %s = %s" % (name, val))
print("\n".join(out))
