; GENERATED by tools/as2dasm.py from fujitest.asm -- do not edit; edit the AS
; source and regenerate. dasm syntax; see the translator for the rules.
; fujitest.asm -- M1: one real transaction, and proof the cart survives a reset.
;
; Asks the FujiNet for GET_ADAPTERCONFIG_EXTENDED and puts the live SSID, IP
; address and firmware version on screen. Nothing is faked: the bytes come off
; a socket to fujinet-pc, through the cartridge's own fujimail.c, and are
; rendered by the cartridge's own compositor.
;
; The reply is 240 bytes and the window is 512, so it lands in slice 0 whole
; and no slice paging is needed -- which is why the reply window is 512 and not
; 256 (see fuji_mailbox.h).
;
; THE TRANSACTION RUNS BEFORE THE DISPLAY STARTS, with the screen blanked.
; Under emulation the socket round trip is synchronous so this is invisible;
; on real hardware it is a brief blank frame before the picture appears. A
; client that wants to stay in sync while it talks has to do its transactions
; from inside the frame loop, which fujicfg will.
;
; Exit test: emu/drive.lua reads the rendered planes back and requires the SSID
; to be on screen; emu/resettest.lua then toggles the RESET switch and requires
; the NEXT sequence number to be ACKSEQ+1, not 1 -- the cart has no reset line,
; so it keeps its state across a console reset and a client that restarted its
; own counter would collide with a sequence already answered.

        processor 6502
        include "vcs2600.h"

; ---------------- zero page ----------------
        IFNCONST PAD3
PAD3    EQU     $81             ; the display kernel's 3-cycle pad target
        ENDIF
        IFNCONST SAVSP
SAVSP   EQU     $82             ; stack pointer, parked across the kernel
        ENDIF
APERR   EQU     $8C             ; what went wrong, if anything

        include "fujinet.h"

; Field offsets inside GET_ADAPTERCONFIG_EXTENDED, from the packed
; AdapterConfigExtended in lib/device/fujiDevice/fujiDevice.h. Every field this
; client wants is below 256, so a single-byte index reaches all of them.
AC_SSID EQU     0               ; char[33]
AC_VER  EQU     125             ; char[15]
AC_SIP  EQU     140             ; char[16], the IP already formatted as text

        ORG     $1000

; ---------------- cold start ----------------
START  sei
        cld
        ldx     #$FF
        txs
        lda     #0
CLRLP  sta     $00,x           ; $00-$7F is the TIA, $80-$FF is RAM
        dex
        bne     CLRLP
        sta     $00

        lda     #2              ; keep the screen blanked while we talk
        sta     VBLANK
        lda     #0
        sta     APERR

; ---------------- the transaction ----------------
        jsr     FNARM           ; open the decode gate
        jsr     FNCHK
        beq     GOTCART
        lda     #FNENOC         ; no cartridge is answering
        sta     APERR
        jmp     SHOW

GOTCART
        lda     #FNDEVF
        sta     FNDEV
        lda     #FNCADPX
        sta     FNCMD
        lda     #0
        sta     FNNPR
        jsr     FNBEG
        jsr     FNGO
        sta     APERR
        cmp     #FNEOK
        bne     SHOW
        jsr     FNACK
        sta     APERR

; ---------------- put it on screen ----------------
SHOW   lda     #<TTITLE
        sta     FNPTRL
        lda     #>TTITLE
        sta     FNPTRH
        lda     #0
        jsr     FNRSTR

        lda     APERR
        beq     SHOWOK

; The failure screen is as useful as the success one: it is what a burned
; EPROM shows when there is no cartridge behind it.
        lda     #<TFAIL
        sta     FNPTRL
        lda     #>TFAIL
        sta     FNPTRH
        lda     #2
        jsr     FNRSTR
        lda     #3
        jsr     FNROWA
        lda     APERR
        jsr     FNHEX
        jsr     FNENDR
        jmp     RUN

SHOWOK lda     #<TSSID
        sta     FNPTRL
        lda     #>TSSID
        sta     FNPTRH
        lda     #2
        jsr     FNRSTR
        lda     #3              ; row
        ldx     #AC_SSID        ; reply offset
        ldy     #FNTCOL         ; at most a rowful
        jsr     FNRRPL

        lda     #<TIP
        sta     FNPTRL
        lda     #>TIP
        sta     FNPTRH
        lda     #5
        jsr     FNRSTR
        lda     #6
        ldx     #AC_SIP
        ldy     #FNTCOL
        jsr     FNRRPL

        lda     #<TVER
        sta     FNPTRL
        lda     #>TVER
        sta     FNPTRH
        lda     #8
        jsr     FNRSTR
        lda     #9
        ldx     #AC_VER
        ldy     #FNTCOL
        jsr     FNRRPL

; The sequence number, in hex. This is the rung's real evidence: after a
; console RESET it must read 02, not 01.
        lda     #<TSEQ
        sta     FNPTRL
        lda     #>TSEQ
        sta     FNPTRH
        lda     #11
        jsr     FNRSTR
        lda     #12
        jsr     FNROWA
        lda     FNACKS
        jsr     FNHEX
        jsr     FNENDR

RUN    lda     #0
        sta     VBLANK
        jsr     DINIT
        jmp     DLOOP

; ---------------- strings ----------------
TTITLE .byte      "FUJINET 2600",0
TSSID  .byte      "SSID",0
TIP    .byte      "IP",0
TVER   .byte      "VERSION",0
TSEQ   .byte      "ACKSEQ",0
TFAIL  .byte      "FAILED ERR",0

        include "fujilib.asm"
APPVBL rts                     ; this client needs no per-frame work

        include "fujidisp.asm"

; ---------------- the fixed tail ----------------
; $1FFC must live in the fixed half so a console RESET is survivable whatever
; bank happens to be mapped low.
        ORG     $1FFC
        .word      START           ; RESET
        .word      START           ; BRK -- a runaway reboots rather than hangs

;        END
