; GENERATED by tools/as2dasm.py from devdefs.inc -- do not edit; edit the AS
; source and regenerate. dasm syntax; see the translator for the rules.
; devdefs.inc -- the other devices, and the FUJI commands the testrom's
; fujinet.inc does not name. Values from include/fujiDeviceID.h and
; include/fujiCommandID.h; the appkey struct from lib/device/fujiDevice/
; AppKeyMixin.h. Kept apart from fujinet.inc so that file stays verbatim.

; ---------------- device ids ----------------
DSKDEV  EQU     $31             ; D1: (D2:-D8: are $32-$38)
PRNDEV  EQU     $40             ; P1:
CLKDEV  EQU     $45             ; the clock (APETIME)
MDMDEV  EQU     $50             ; R: the modem
CPMDEV  EQU     $5A             ; CP/M

; ---------------- FUJI ($70) commands ----------------
FNCRST  EQU     $FF             ; RESET
FNCGSSD EQU     $FE             ; GET_SSID
FNCSCAN EQU     $FD             ; SCAN_NETWORKS
FNCSCNR EQU     $FC             ; GET_SCAN_RESULT
FNCSSSD EQU     $FB             ; SET_SSID
FNCWIFI EQU     $FA             ; GET_WIFISTATUS
FNCWHST EQU     $F3             ; WRITE_HOST_SLOTS
FNCRDEV EQU     $F2             ; READ_DEVICE_SLOTS
FNCWDEV EQU     $F1             ; WRITE_DEVICE_SLOTS
FNCWIEN EQU     $EA             ; GET_WIFI_ENABLED
FNCUIMG EQU     $E9             ; UNMOUNT_IMAGE
FNCADPC EQU     $E8             ; GET_ADAPTERCONFIG
FNCNEWD EQU     $E7             ; NEW_DISK
FNCUHST EQU     $E6             ; UNMOUNT_HOST
FNCGDPS EQU     $E5             ; GET_DIRECTORY_POSITION
FNCSHPX EQU     $E1             ; SET_HOST_PREFIX
FNCGHPX EQU     $E0             ; GET_HOST_PREFIX
FNCAKWR EQU     $DE             ; WRITE_APPKEY
FNCAKRD EQU     $DD             ; READ_APPKEY
FNCAKOP EQU     $DC             ; OPEN_APPKEY
FNCAKCL EQU     $DB             ; CLOSE_APPKEY
FNCGDFP EQU     $DA             ; GET_DEVICE_FULLPATH
FNCCBOT EQU     $D9             ; CONFIG_BOOT
FNCCOPY EQU     $D8             ; COPY_FILE
FNCMALL EQU     $D7             ; MOUNT_ALL
FNCSBM  EQU     $D6             ; SET_BOOT_MODE
FNCRAND EQU     $D3             ; RANDOM_NUMBER
FNCB64EI EQU    $D0             ; BASE64_ENCODE_INPUT
FNCB64EC EQU    $CF             ; BASE64_ENCODE_COMPUTE
FNCB64EL EQU    $CE             ; BASE64_ENCODE_LENGTH
FNCB64EO EQU    $CD             ; BASE64_ENCODE_OUTPUT
FNCB64DI EQU    $CC             ; BASE64_DECODE_INPUT
FNCB64DC EQU    $CB             ; BASE64_DECODE_COMPUTE
FNCB64DL EQU    $CA             ; BASE64_DECODE_LENGTH
FNCB64DO EQU    $C9             ; BASE64_DECODE_OUTPUT
FNCHSHI EQU     $C8             ; HASH_INPUT
FNCHSHC EQU     $C7             ; HASH_COMPUTE
FNCHSHL EQU     $C6             ; HASH_LENGTH
FNCHSHO EQU     $C5             ; HASH_OUTPUT
FNCHSHN EQU     $C3             ; HASH_COMPUTE_NO_CLEAR
FNCHSHX EQU     $C2             ; HASH_CLEAR
FNCQRO  EQU     $BF             ; QRCODE_OUTPUT
FNCQRL  EQU     $BE             ; QRCODE_LENGTH
FNCQRE  EQU     $BD             ; QRCODE_ENCODE
FNCQRI  EQU     $BC             ; QRCODE_INPUT
FNCGUID EQU     $BB             ; GENERATE_GUID
FNCSTAT EQU     $53             ; STATUS
FNCRDY  EQU     $00             ; DEVICE_READY

; ---------------- appkeys ----------------
; OPEN_APPKEY's payload is ONE six-byte packed struct: creator (u16, little-
; endian), app, key, mode, and a reserved byte that is not optional.
AKMRD   EQU     0               ; mode: read
AKMWR   EQU     1               ; mode: write
AKCREAT EQU     1               ; the shared FujiNet username slot...
AKAPP   EQU     1               ; ...creator 1, app 1, key 0, which every
AKKEY   EQU     0               ; game in the family reads

; ---------------- the clock ($45) ----------------
CKGTIME EQU     $93             ; GETTIME: 7 bytes, binary
CKISOL  EQU     $49             ; 'I' GET_ISO_LOCAL: "YYYY-MM-DDTHH:MM:SS"...
CKISOU  EQU     $5A             ; 'Z' GET_ISO_UTC
CKGEN   EQU     $47             ; 'G' GET_GENERAL
CKTZLEN EQU     $4C             ; 'L' GETTZ_LEN
CKSETTZ EQU     $99             ; SETTZ: payload = the POSIX TZ string
CKTZTIM EQU     $9A             ; GETTZTIME

; ---------------- hash algorithms (HASH_COMPUTE's parameter) ----------------
HAMD5   EQU     0
HASHA1  EQU     1
HASHA256 EQU    3
HASHA512 EQU    4

; ---------------- the path buffers, beyond the testrom's four ops ----------------
FP_POPCH EQU    4               ; drop ONE character (the keyboard's backspace)
FP_SEL0 EQU     5               ; subsequent ops act on buffer 0...
FP_SEL1 EQU     6
FP_SEL2 EQU     7
FP_SEL3 EQU     8               ; ...buffer 3, the edit scratch
FP_CMIT EQU     9               ; selected <- the edit scratch
FP_SEED EQU     10              ; the edit scratch <- selected

; ---------------- the blit port ----------------
FH_BSL  EQU     $F5             ; source offset, low (into the reply window)
FH_BSH  EQU     $F6             ; source offset, high
FH_BDL  EQU     $F7             ; destination offset, low (into the planes)
FH_BDH  EQU     $F8             ; destination offset, high
FH_BCNT EQU     $F9             ; count
FH_BGO  EQU     $FA             ; data = the transform: fire
FNBGEN  EQU     $1F19           ; FN_B_BLITGEN: bumped when a blit has landed
FB_RAW  EQU     0               ; copy bytes unchanged
FB_TEXT EQU     1               ; ASCII -> a text row
FB_FIELD EQU    2               ; a 10x10 game field -> ten text rows
FB_HULLS EQU    3               ; five placements -> a hull overlay
FB_SEA  EQU     4               ; fill the composed board with sea
FB_CELL EQU     5               ; board[cnt] = the low byte of src
FB_PAINT EQU    6               ; paint the composed board into ten rows
FB_PATH EQU     7               ; cnt chars of the path buffer into a row
FB_TCELL EQU    8               ; ONE character into ONE cell
FB_CARD EQU     9               ; one seat's five cards
FB_PFCLR EQU    10              ; clear kinds (src mask) in a playfield slot
FB_PFLD EQU     11              ; a game field -> a playfield slot's HIT/MID
FB_PFHUL EQU    12              ; placements -> a slot's AUX
FB_PFCEL EQU    13              ; one cell of a slot: set or clear kinds

; ---------------- the playfield tables ----------------
PFROW0  EQU     30              ; the first table byte of every plane
PFKLEN  EQU     20              ; entries per table: cell rows 0-19
PFM_HIT EQU     $01             ; the kind masks PFCLR and PFCEL take
PFM_MID EQU     $02
PFM_AUX EQU     $04
PFM_ALL EQU     $07
PFM_CLR EQU     $80             ; PFCEL: clear the bits instead of set
PFSLOTS EQU     4
