; GENERATED by tools/as2dasm.py from netdefs.inc -- do not edit; edit the AS
; source and regenerate. dasm syntax; see the translator for the rules.
; netdefs.inc -- the N: (network) device, for the client library.
;
; Device ids from include/fujiDeviceID.h, command bytes from
; include/fujiCommandID.h, open modes from lib/network-protocol/HTTP.cpp and
; the STATUS reply layout from lib/device/rs232/network.cpp. The testrom's
; fujinet.inc covers the FUJI device only; this is the rest of what a client
; that talks to the network needs, kept separate so that file stays verbatim.
NETDEV  EQU     $71             ; N1: (N2:-N8: are $72-$78)
NCOPEN  EQU     $4F             ; 'O' open: params mode, translation; payload = devicespec
NCCLOSE EQU     $43             ; 'C' close
NCREAD  EQU     $52             ; 'R' read: ONE two-byte param, the count
NCWRITE EQU     $57             ; 'W' write: ONE two-byte param, then the payload
NCSTAT  EQU     $53             ; 'S' status: two one-byte params, both 0
NCPARSE EQU     $50             ; 'P' parse the reply as JSON
NCQUERY EQU     $51             ; 'Q' query a JSON path; payload = the path
NCJSON  EQU     $FC             ; channel mode: second param 0 = protocol, 1 = JSON
NCHTTPM EQU     $4D             ; 'M' HTTP channel mode: second param 0 body, 1 collect
                                ;   headers, 2 get headers, 3 set headers, 4 POST data
NMREAD  EQU     4               ; open mode: read (HTTP GET)
NMWRITE EQU     8               ; write (HTTP PUT)
NMHTTPG EQU     12              ; read/write (HTTP GET, headers allowed)
NMPOST  EQU     13              ; HTTP POST
NTRNONE EQU     0               ; translation: none
NTRCR   EQU     1               ; CR to/from the host's EOL
NTRLF   EQU     2               ; LF
NTRCRLF EQU     3               ; CR LF
NSAVLO  EQU     0               ; STATUS reply: bytes waiting, low
NSAVHI  EQU     1               ;   high
NSCONN  EQU     2               ;   connected
NSDEVST EQU     3               ;   nDevStatus_t: 1 = success
