#ifdef BUILD_NES

/**
 * @brief   NES Graphics Routines for 5cardstud
 * @author  Thomas Cherryhomes
 * @email   thom dot cherryhomes at gmail dot com
 * @license gpl v. 3, see LICENSE for details
 * @verbose PPU background layer. The NES has no per-cell colour, so every
 *          glyph+colour pair the ColecoVision port draws is one tile here
 *          (src/nes/tiles.h, generated by mkchr.py from that port's font and
 *          card art). Writes go through cc65's vblank ring buffer; a shadow
 *          of the glyph codes stands in for the TMS9918 ports' cvpeek().
 */

#include <stdbool.h>
#include <string.h>
#include <joystick.h>
#include "tiles.h"
#include "vars.h"
#include "../platform-specific/graphics.h"

#define CORNER_TOP 0
#define CORNER_BOTTOM 18

#define PPU_CTRL   (*(volatile unsigned char *) 0x2000)
#define PPU_MASK   (*(volatile unsigned char *) 0x2001)
#define PPU_STATUS (*(volatile unsigned char *) 0x2002)
#define PPU_SCROLL (*(volatile unsigned char *) 0x2005)
#define PPU_ADDR   (*(volatile unsigned char *) 0x2006)
#define PPU_DATA   (*(volatile unsigned char *) 0x2007)

#define NT_BASE    0x2000
#define ROW0       2                /* game row 0 is nametable row 2 (overscan) */
#define STATUS_ROW (HEIGHT - 1)
#define NO_TILE    0xFF             /* a padding blank mkchr.py never hands out */

/* Palette 0: felt, white, red, black. Palette 1 is the same with grey for
   white: the viewer's hidden hole card, as the Atari client shades it. */
#define PAL_FELT  0x0A
#define PAL_WHITE 0x30
#define PAL_GREY  0x10
#define PAL_RED   0x16
#define PAL_BLACK 0x0F

#define AT_BASE   0x23C0

void __fastcall__ ppu_put(unsigned int addr, unsigned char val);   /* ppu.s */

bool always_render_full_cards = 0;

/* What each cell shows, as a glyph code (ASCII or UDG_*). */
static unsigned char shadow[HEIGHT][WIDTH];

/* The nametable's attribute bytes, so a palette change writes only on change. */
static unsigned char attr[64];

/* Palette pal for the 2x2 block holding game cell (x,y). */
static void setBlockPalette(unsigned char x, unsigned char y, unsigned char pal)
{
    unsigned char row = y + ROW0;
    unsigned char i = ((row >> 2) << 3) | (x >> 2);
    unsigned char shift = ((row & 2) << 1) | (x & 2);
    unsigned char v = (attr[i] & ~(3 << shift)) | (pal << shift);

    if (v != attr[i])
    {
        attr[i] = v;
        ppu_put(AT_BASE + i, v);
    }
}

/* Grey (or not) the card face at x..x+1, rows y..y+4. Only an even x lines up
   with the attribute grid; seat 0's hole card always does (vars.c). */
static void shadeCard(unsigned char x, unsigned char y, bool grey)
{
    unsigned char i;

    if (x & 1)
        return;
    for (i = 0; i < 5; i += 2)
        setBlockPalette(x, y + i, grey);
}

static void put(unsigned char x, unsigned char y, unsigned char glyph, unsigned char tile)
{
    if (x >= WIDTH || y >= HEIGHT)
        return;
    shadow[y][x] = glyph;
    ppu_put(NT_BASE + ((unsigned int)(y + ROW0) << 5) + x, tile);
}

static unsigned char peek(unsigned char x, unsigned char y)
{
    if (x >= WIDTH || y >= HEIGHT)
        return ' ';
    return shadow[y][x];
}

/* Fold to the font's upper-case range; anything else prints as '?'. */
static unsigned char textGlyph(unsigned char c)
{
    if (c >= 'a' && c <= 'z')
        c -= 'a' - 'A';
    if (c < 0x20 || c > 0x5F)
        c = '?';
    return c;
}

static void putText(unsigned char x, unsigned char y, const char *s, unsigned char base)
{
    unsigned char c;

    while ((c = (unsigned char) *s++) != 0 && x < WIDTH)
    {
        c = textGlyph(c);
        put(x++, y, c, base + (c - 0x20));
    }
}

/**
 * @brief Initialize graphics mode; set palette.
 */
void initGraphics()
{
    unsigned int i;

    joy_install(joy_static_stddrv);

    // PPU warm-up: two vblanks with rendering off before touching VRAM.
    PPU_CTRL = 0;
    PPU_MASK = 0;
    while (!(PPU_STATUS & 0x80)) ;
    while (!(PPU_STATUS & 0x80)) ;

    PPU_ADDR = 0x3F;
    PPU_ADDR = 0x00;
    for (i = 0; i < 8; i++)
    {
        PPU_DATA = PAL_FELT;
        PPU_DATA = i == 1 ? PAL_GREY : PAL_WHITE;
        PPU_DATA = PAL_RED;
        PPU_DATA = PAL_BLACK;
    }

    // Nametable 0: blanks on felt for the 24 game rows, black blanks in the
    // overscan rows above and below (the TMS9918 ports' border); palette 0
    // everywhere.
    PPU_ADDR = 0x20;
    PPU_ADDR = 0x00;
    for (i = 0; i < 960; i++)
        PPU_DATA = (i < ROW0 * 32 || i >= (ROW0 + HEIGHT) * 32) ? T_STATUS : T_TEXT;
    for (i = 0; i < 64; i++)
        PPU_DATA = 0;
    memset(shadow, ' ', sizeof shadow);
    memset(attr, 0, sizeof attr);

    PPU_SCROLL = 0;
    PPU_SCROLL = 0;
    PPU_ADDR = 0;
    PPU_ADDR = 0;
    PPU_CTRL = 0x90;            /* NMI on; background tiles from $1000 (CHARS1) */
    PPU_MASK = 0x0A;            /* background on, left column shown */
    waitvsync();
}

void drawChip(unsigned char x, unsigned char y)
{
    put(x, y, UDG_CHIP, T_CHIP_RG);
}

void drawBuffer()
{
}

void drawBox(unsigned char x, unsigned char y, unsigned char w, unsigned char h)
{
    unsigned char i;
    // Correct coordinates;
    w++;
    h++;

    // Put box corners at coordinate extents
    put(x, y, UDG_BOX_TL, T_BOX_TL_RG);
    put(x + w, y, UDG_BOX_TR, T_BOX_TR_RG);
    put(x, y + h, UDG_BOX_BL, T_BOX_BL_RG);
    put(x + w, y + h, UDG_BOX_BR, T_BOX_BR_RG);

    // Horizontal rules
    for (i = 1; i < w; i++)
    {
        put(x + i, y, UDG_BOX_H, T_BOX_H_RG);
        put(x + i, y + h, UDG_BOX_H, T_BOX_H_RG);
    }

    // Vertical rules
    for (i = 1; i < h; i++)
    {
        put(x, y + i, UDG_BOX_V, T_BOX_V_RG);
        put(x + w, y + i, UDG_BOX_V, T_BOX_V_RG);
    }
}

/**
 * @brief Draw text s at position x,y
 * @param x Horizontal position (0-31)
 * @param y Vertical Position (0-23)
 * @param s NULL terminated string to display.
 */
void drawText(unsigned char x, unsigned char y, const char* s)
{
    putText(x, y, s, T_TEXT);
}

/**
 * @brief Draw the 5 Card Stud Logo
 */
void drawLogo()
{
    unsigned char i = 4;
    drawText(WIDTH/2-5,++i, "           ");
    drawText(WIDTH/2-5,++i, " FUJI  NET ");
    drawText(WIDTH/2-5,++i, "           ");
    drawText(WIDTH/2-5,++i, "5 CARD STUD");
    drawText(WIDTH/2-5,++i, "           ");
}

/* Set while a two-line status message has taken row 22 for the bar. */
static bool tallStatus;

void clearStatusBar()
{
    unsigned char x;
    // Row 23 only; row 22 is otherwise left alone, as the border aces extend
    // into it -- unless a two-line message took it, when it goes back to felt.
    for (x = 0; x < WIDTH; x++)
        put(x, STATUS_ROW, ' ', T_STATUS);
    if (tallStatus)
    {
        tallStatus = false;
        put(0, 22, UDG_SCREEN_BL, T_SCREEN_BL_GK);
        for (x = 1; x < WIDTH-1; x++)
            put(x, 22, ' ', T_TEXT);
        put(WIDTH-1, 22, UDG_SCREEN_BR, T_SCREEN_BR_GK);
    }
}

/**
 * @brief Clear the screen
 */
void resetScreen()
{
    unsigned char x, y;

    for (y = 0; y < STATUS_ROW; y++)
        for (x = 0; x < WIDTH; x++)
            put(x, y, ' ', T_TEXT);
    clearStatusBar();
    for (x = 0; x < sizeof attr; x++)
        if (attr[x])
        {
            attr[x] = 0;
            ppu_put(AT_BASE + x, 0);
        }

    // Round the felt off against the border/status bar, like the MS-DOS build.
    put(0, 0, UDG_SCREEN_TL, T_SCREEN_TL_GK);
    put(WIDTH-1, 0, UDG_SCREEN_TR, T_SCREEN_TR_GK);
    put(0, 22, UDG_SCREEN_BL, T_SCREEN_BL_GK);
    put(WIDTH-1, 22, UDG_SCREEN_BR, T_SCREEN_BR_GK);
}

void disableDoubleBuffer()
{
}

void enableDoubleBuffer()
{
}

/**
 * @brief Draw card at position x,y
 * @param x Horizontal card position (0-31)
 * @param y Vertical card position (0-23)
 * @param partial enum (see ../platform-specific/graphics.h)
 * @param s String indicating number and suit. (e.g. "as" for ace of spades)
 * @param isHidden is card currently overturned?
 */
void drawCard(unsigned char x, unsigned char y, unsigned char partial, const char* s, unsigned char isHidden)
{
    unsigned char val, suit, suitTile, rankBase, i;

    if (x==WIDTH-3 && s[0]!='?' && peek(x,y+1)==UDG_BACK_L_TOP) {
        drawCard(x+1,y,PARTIAL_RIGHT,"??",false);
    }

    if (partial == PARTIAL_LEFT)
    {
        put(x, y++, UDG_CARD_TL, T_CARD_TL_RG);
        put(x, y++, UDG_BACK_L_TOP, T_BACK_L_TOP_RW);
        put(x, y++, UDG_BACK_L_MID, T_BACK_L_MID_RW);
        put(x, y++, UDG_BACK_L_BOT, T_BACK_L_BOT_RW);
        put(x, y++, UDG_CARD_BL, T_CARD_BL_RG);
    }
    else if (partial == PARTIAL_RIGHT)
    {
        x++;
        put(x, y++, UDG_CARD_TOP_TRIM, T_CARD_TOP_TRIM_RG);
        put(x, y++, UDG_BACK_RCOL_TOP, T_BACK_RCOL_TOP_RW);
        put(x, y++, UDG_BACK_RCOL_MID, T_BACK_RCOL_MID_RW);
        put(x, y++, UDG_BACK_RCOL_BOT, T_BACK_RCOL_BOT_RW);
        put(x, y++, UDG_CARD_BOT_TRIM, T_CARD_BOT_TRIM_RG);
    }
    else // FULL CARD
    {
        // A hidden hole card is greyed, rather than banded, where it can be.
        shadeCard(x, y, isHidden && s[0] != '?');

        switch (s[1])
        {
        case 'h' :
            suit=UDG_SUIT_HEART;
            suitTile=T_SUIT_HEART_RW;
            rankBase=T_RANK_RW;
            break;
        case 'd' :
            suit=UDG_SUIT_DIAMOND;
            suitTile=T_SUIT_DIAMOND_RW;
            rankBase=T_RANK_RW;
            break;
        case 'c' :
            suit=UDG_SUIT_CLUB;
            suitTile=T_SUIT_CLUB_KW;
            rankBase=T_RANK_KW;
            break;
        case 's' :
            suit=UDG_SUIT_SPADE;
            suitTile=T_SUIT_SPADE_KW;
            rankBase=T_RANK_KW;
            break;
        default:
            suit=UDG_CARD_VERT;         // Something wrong.
            suitTile=T_CARD_VERT_RW;
            rankBase=T_RANK_RW;
            break;
        }

        // If card is overturned, draw the back
        if (s[0]=='?')
        {
            // Shift right card left one for easy drawing of border
            // As well as clear existing cards, assuming a fold
            if (x>WIDTH-3) {
                for (i=0;i<5;i++)
                    putText(x-7,y+i,"      ",T_TEXT);
                x--;
            } else {
                for (i=0;i<5;i++)
                    putText(x+3,y+i,"       ",T_TEXT);
            }
            put(x, y, UDG_CARD_TL, T_CARD_TL_RG);
            put(x+1, y, UDG_CARD_TOP, T_CARD_TOP_RG);
            put(x+2, y, UDG_CARD_TR_STUB, T_CARD_TR_STUB_RG);
            y++;
            put(x, y, UDG_BACK_L_TOP, T_BACK_L_TOP_RW);
            put(x+1, y, UDG_BACK_R_TOP, T_BACK_R_TOP_RW);
            put(x+2, y, UDG_CARD_VERT, T_CARD_VERT_RG);
            y++;
            put(x, y, UDG_BACK_L_MID, T_BACK_L_MID_RW);
            put(x+1, y, UDG_BACK_R_MID, T_BACK_R_MID_RW);
            put(x+2, y, UDG_CARD_VERT, T_CARD_VERT_RG);
            y++;
            put(x, y, UDG_BACK_L_BOT, T_BACK_L_BOT_RW);
            put(x+1, y, UDG_BACK_R_BOT, T_BACK_R_BOT_RW);
            put(x+2, y, UDG_CARD_VERT, T_CARD_VERT_RG);
            y++;
            put(x, y, UDG_CARD_BL, T_CARD_BL_RG);
            put(x+1, y, UDG_CARD_BOT, T_CARD_BOT_RG);
            put(x+2, y, UDG_CARD_BR_STUB, T_CARD_BR_STUB_RG);
        }
        else // Draw the full card.
        {
            // Top card border
            if (peek(x+1,y)!=UDG_CARD_TOP)
            {
                put(x, y, UDG_CARD_TL, T_CARD_TL_RG);
                put(x+1, y, UDG_CARD_TOP, T_CARD_TOP_RG);
            }
            if (peek(x+2,y)==' ')
                put(x+2, y, UDG_CARD_TR_STUB, T_CARD_TR_STUB_RG);

            switch (s[0])
            {
            case 't':
                val=UDG_RANK_T; // 10
                break;
            case 'j':
                val=UDG_RANK_J;
                break;
            case 'q':
                val=UDG_RANK_Q;
                break;
            case 'k':
                val=UDG_RANK_K;
                break;
            case 'a':
                val=UDG_RANK_A;
                break;
            default:
                val=UDG_RANK_2+(s[0]-'2');
                break;
            }

            // Left border and card value
            y++;
            put(x, y, UDG_CARD_VERT, T_CARD_VERT_RW);
            put(x+1, y, val, rankBase + (val - UDG_RANK_2));
            if (peek(x+2,y)==' ')
                put(x+2, y, UDG_CARD_VERT, T_CARD_VERT_RG);

            // Interior (hole-card marker band if hidden)
            y++;
            if (isHidden && (x & 1))
            {
                put(x, y, UDG_HIDDEN_L, T_HIDDEN_L_RW);
                put(x+1, y, UDG_HIDDEN_R, T_HIDDEN_R_RW);
            }
            else
            {
                put(x, y, UDG_CARD_VERT, T_CARD_VERT_RW);
                put(x+1, y, ' ', T_BLANK_W);
            }
            if (peek(x+2,y)==' ')
                put(x+2, y, UDG_CARD_VERT, T_CARD_VERT_RG);

            // Suit
            y++;
            put(x, y, UDG_CARD_VERT, T_CARD_VERT_RW);
            put(x+1, y, suit, suitTile);
            if (peek(x+2,y)==' ')
                put(x+2, y, UDG_CARD_VERT, T_CARD_VERT_RG);

            // Bottom border
            y++;
            if (peek(x+1,y)!=UDG_CARD_BOT)
            {
                put(x, y, UDG_CARD_BL, T_CARD_BL_RG);
                put(x+1, y, UDG_CARD_BOT, T_CARD_BOT_RG);
            }
            if (peek(x+2,y)==' ')
                put(x+2, y, UDG_CARD_BR_STUB, T_CARD_BR_STUB_RG);
        }
    }
}

/* Up to n characters of s on the status bar, white on black. */
static void putStatus(unsigned char x, unsigned char y, const char *s, unsigned char n)
{
    unsigned char c;

    while (n-- && (c = (unsigned char) *s++) != 0 && x < WIDTH)
    {
        c = textGlyph(c);
        put(x++, y, c, T_STATUS + (c - 0x20));
    }
}

/* A message too long for one row (the round result) takes row 22 into the
   bar as well, word-wrapped across the two. */
void drawStatusTextAt(unsigned char x, const char* s)
{
    unsigned char brk, i;

    if (strlen(s) <= WIDTH)
    {
        putStatus(x, STATUS_ROW, s, WIDTH);
        return;
    }

    for (brk = WIDTH; brk > 0 && s[brk] != ' '; brk--) ;
    if (brk == 0)
        brk = WIDTH;

    tallStatus = true;
    for (i = 0; i < WIDTH; i++)
    {
        put(i, 22, ' ', T_STATUS);
        put(i, STATUS_ROW, ' ', T_STATUS);
    }
    putStatus(0, 22, s, brk);
    putStatus(0, STATUS_ROW, s + brk + (s[brk] == ' '), WIDTH);
}

void drawStatusText(const char* s)
{
    clearStatusBar();
    drawStatusTextAt(0, s);
}

unsigned char cycleNextColor()
{
    return 0;
}

void drawStatusTimer()
{
}

/* The highlighted or plain tile for what a cell shows: a red underline on the
   status row (the move under the cursor), a red bar across the top of the row
   under the active player's name elsewhere -- blank cells, or the tops of that
   player's cards. Cells with no highlight variant are left alone. */
static unsigned char lineTile(unsigned char g, unsigned char y, bool on)
{
    if (y == STATUS_ROW)
    {
        if (g < 0x20 || g > 0x5F)
            return NO_TILE;
        if (!on)
            return T_STATUS + (g - 0x20);
        if (g == ' ')
            return T_STATUS_UL;
        if (g >= '0' && g <= '9')
            return T_STATUS_UL + 1 + (g - '0');
        if (g >= 'A' && g <= 'Z')
            return T_STATUS_UL + 11 + (g - 'A');
        return NO_TILE;
    }
    switch (g)
    {
    case ' ':               return on ? T_TOPBAR_SPACE : T_TEXT;
    case UDG_CARD_TL:       return on ? T_TOPBAR_CARD_TL : T_CARD_TL_RG;
    case UDG_CARD_TOP:      return on ? T_TOPBAR_CARD_TOP : T_CARD_TOP_RG;
    case UDG_CARD_TR_STUB:  return on ? T_TOPBAR_CARD_TR_STUB : T_CARD_TR_STUB_RG;
    case UDG_CARD_TOP_TRIM: return on ? T_TOPBAR_CARD_TOP_TRIM : T_CARD_TOP_TRIM_RG;
    }
    return NO_TILE;
}

static void line(unsigned char x, unsigned char y, unsigned char w, bool on)
{
    unsigned char t;

    if (y >= HEIGHT)
        return;
    for (; w != 0 && x < WIDTH; w--, x++)
    {
        t = lineTile(shadow[y][x], y, on);
        if (t != NO_TILE)
            ppu_put(NT_BASE + ((unsigned int)(y + ROW0) << 5) + x, t);
    }
}

void hideLine(unsigned char x, unsigned char y, unsigned char w)
{
    line(x, y, w, false);
}

void drawLine(unsigned char x, unsigned char y, unsigned char w)
{
    line(x, y, w, true);
}

void setColorMode(unsigned char mode)
{
}

void drawBorder()
{
    drawCard(1,CORNER_TOP,FULL_CARD, "as", 0);
    drawCard(WIDTH-3,CORNER_TOP,FULL_CARD, "ah", 0);
    drawCard(1,CORNER_BOTTOM,FULL_CARD, "ad", 0);
    drawCard(WIDTH-3,CORNER_BOTTOM,FULL_CARD, "ac", 0);
}

#endif /* BUILD_NES */
