#ifdef BUILD_NES

#ifndef KEYMAP_H
#define KEYMAP_H

#include <joystick.h>

// Screen dimensions and layout for platform. The NES shows 32x30 tiles; the
// game is 32x25, drawn three rows down (src/nes/graphics.c ROW0) so it sits
// inside a CRT's overscan. 25 rows is the MS-DOS height, so the board, the
// dice row and the status line keep the MS-DOS client's vertical layout; 32
// columns is the Adam/CoCo width, and the MS-DOS board shifted eight cells
// left lands exactly on the Adam board's columns (SCORES_X 2, dividers 7-31).
#define WIDTH 32
#define HEIGHT 25

#define ROLL_SOUND_MOD 1 // How often to play roll sound
#define ROLL_FRAMES 11   // How many roll frames to play
#define BOTTOM_HEIGHT 4  // How high the bottom panel is
#define SCORES_X 2       // X start of scoreboard
#define GAMEOVER_PROMPT_Y HEIGHT-3
// WIDTH-25, the MS-DOS placement: gamelogic.c puts the dice cursor for the
// roll button at WIDTH-25 and the dice at WIDTH-20+4*i.
#define ROLL_X WIDTH-25
#define TIMER_X 5
#define TIMER_NUM_OFFSET_X 2
#define TIMER_NUM_OFFSET_Y 1

#define QUERY_SUFFIX "" // 6502 is little endian - no &be=1 needed

// Icons - MS-DOS charset glyph numbers; graphics.c maps them through
// sheetTile[] (src/nes/tiles.h, generated by mkchr.py)
#define ICON_TEXT_CURSOR  0xD9
#define ICON_MARK         0x1D
#define ICON_MARK_ALT     0x1C
#define ICON_PLAYER       0x0A
#define ICON_SPEC         0xDC
#define ICON_CURSOR       0xBE
#define ICON_CURSOR_ALT   0xBF
#define ICON_CURSOR_BLIP  0x3E

/* readJoystick() (src/nes/input.c) returns the d-pad only, as cc65's joystick
   driver bits. The buttons never appear in the joystick byte: input.c reports
   them as key codes behind kbhit()/cgetc(), with one edge detector, so a held
   button reports exactly once. A is KEY_RETURN, which readCommonInput() maps
   to the trigger and which also satisfies the screens that block on cgetc()
   ("press any key"). cc65's <joystick.h> defines JOY_UP() and friends
   already; the buttons are overridden to never fire. */
#undef JOY_BTN_1
#undef JOY_BTN_2
#define JOY_BTN_1(v) ((v) & 0)
#define JOY_BTN_2(v) ((v) & 0)

/**
 * Platform specific key map for common input
 */

// There is no keyboard: a d-pad and A, B, SELECT, START. Direction comes from
// the d-pad, never from a key, so the arrow codes are deliberately unreachable
// placeholders -- they exist because readCommonInput() switches on all twelve.
#define KEY_LEFT_ARROW      0xF1
#define KEY_LEFT_ARROW_2    0xF2
#define KEY_LEFT_ARROW_3    0xF3

#define KEY_RIGHT_ARROW     0xF4
#define KEY_RIGHT_ARROW_2   0xF5
#define KEY_RIGHT_ARROW_3   0xF6

#define KEY_UP_ARROW        0xF7
#define KEY_UP_ARROW_2      0xF8
#define KEY_UP_ARROW_3      0xF9

#define KEY_DOWN_ARROW      0xFA
#define KEY_DOWN_ARROW_2    0xFB
#define KEY_DOWN_ARROW_3    0xFC

#define KEY_RETURN       0x0D
#define KEY_ESCAPE       0x1B
#define KEY_ESCAPE_ALT   0x03
#define KEY_SPACEBAR     0x20
#define KEY_BACKSPACE    0x08

// One controller, so one local player: the local player setup screen wants
// the keys 1-4 and A, which a pad cannot type.
#define SINGLE_LOCAL_PLAYER

// Name entry types from an on-screen letter grid (src/nes/osk.c). While it is
// open, kbhit()/cgetc() report what the grid types instead of the buttons.
#define ON_SCREEN_KEYBOARD
void oskOpen(void);
void oskClose(void);

// Button names for the shared screens' prompts (see input.c for the map).
#define ESCAPE "START"
#define ESC "START"
#define TRIGGER_TEXT "A"
#define LOBBY_STATUS_TEXT "B:help SEL:refresh SEL+ST:quit"
#define MENU_QUIT_TEXT "SEL+ST:quit table"
#define MENU_HELP_TEXT "B:how to play"
#define MENU_SOUND_ON_TEXT "SEL+B:sound ON "
#define MENU_SOUND_OFF_TEXT "SEL+B:sound OFF"
#define MENU_ESC_TEXT "START:keep playing"

#endif /* KEYMAP_H */

#endif /* BUILD_NES */
